bridgetownrb/bridgetown

- bridgetown-core/lib/site_template/package.json
- bridgetown-core/lib/site_template/webpack.config.js
- bridgetown-website/package.json
- bridgetown-website/webpack.config.js
Was testing out a site with React added and had to make a few adjustments to the Webpack config. This should do the trick.
> Update webpack and package.json to support JSX

- CHANGELOG.md
- bridgetown-core/lib/bridgetown-core/plugin_manager.rb
- bridgetown-core/lib/bridgetown-core/version.rb
> Release 0.14.1 with patch to fix PluginManager

- bridgetown-core/bridgetown-core.gemspec
- bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb
- bridgetown-core/lib/bridgetown-core/commands/console.rb
- bridgetown-core/lib/bridgetown-core/commands/serve.rb
- bridgetown-core/lib/bridgetown-core/page.rb
- bridgetown-core/lib/bridgetown-core/tags/include.rb
AwesomePrint provides a great experience in the console for displaying data, so let's use it!
Also refactored the GitHub regex a bit in the Apply command and brought back the --no-watch option for the Serve command.
> Use AwesomePrint gem for console

- bridgetown-website/src/_docs/testing.md
Added Cypress testing instructions. Feel free to edit, review, change, whatever the case may be.
> Added documentation for Cypress testing

- bridgetown-core/lib/bridgetown-core/liquid_renderer/file_system.rb
> Resolve deprecation warnings for Ruby 2.7

- bridgetown-website/src/_docs/erb-and-beyond.md
- bridgetown-website/src/_docs/jamstack.md
- bridgetown-website/src/_docs/liquid.md
- bridgetown-website/src/_docs/philosophy.md
- bridgetown-website/src/_docs/variables.md
Documentation to follow up for #79
> Documentation for ERB templates

- bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb
- bridgetown-core/lib/bridgetown-core/utils.rb
- bridgetown-core/test/test_utils.rb
> Call GitHub API to determain default branch name

- bridgetown-website/frontend/fonts/inter.css
- bridgetown-website/src/_components/shared/head.liquid
> Try out a couple of improvements for Lighthouse score

- bridgetown-core/bridgetown-core.gemspec
- bridgetown-core/lib/bridgetown-core/commands/console.rb
> Switch from AwesomePrint to AmazingPrint

- bridgetown-core/features/rendering.feature
- bridgetown-core/lib/bridgetown-core/concerns/site/renderable.rb
- bridgetown-core/lib/bridgetown-core/configuration.rb
- bridgetown-website/src/_docs/configuration/options.md
- bridgetown-website/src/_docs/front-matter.md
> Switch to processing Ruby front matter by default

- bridgetown-core/lib/bridgetown-core/utils.rb
- bridgetown-core/test/test_utils.rb
Fixes #67 
Simple port of the related Jekyll fix by @swanson
> Add international character slug improvements by Matt Swanson

- bridgetown-core/lib/bridgetown-core/filters.rb
- bridgetown-core/lib/bridgetown-core/filters/condition_helpers.rb
- bridgetown-core/lib/bridgetown-core/tags/find.rb
- bridgetown-core/test/test_tags.rb
- bridgetown-website/src/_layouts/docs.liquid
> Provide a Liquid find tag as easier alternative to where_exp

- bridgetown-builder/lib/bridgetown-builder/dsl/liquid.rb
- bridgetown-builder/test/test_filters_dsl.rb
> Execute block-based filters within object scope

- bridgetown-builder/lib/bridgetown-builder/dsl/helpers.rb
- bridgetown-builder/lib/bridgetown-builder/plugin.rb
- bridgetown-builder/test/test_helpers_dsl.rb
- bridgetown-website/src/_docs/erb-and-beyond.md
- bridgetown-website/src/_docs/plugins.md
- bridgetown-website/src/_docs/plugins/filters.md
- bridgetown-website/src/_docs/plugins/helpers.md
Closes #134 
Adds new documentation about custom helpers as well as clarifies the relationship between helpers and Liquid tags/filters.
> Helper DSL for plugins

- bridgetown-core/lib/bridgetown-core/page.rb
- bridgetown-core/lib/bridgetown-core/renderer.rb
- bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
- bridgetown-paginate/lib/bridgetown-paginate/pagination_model.rb
Aliases Pager to Paginator...wasnt sure where to get started adding tests for this. I couldnt find anything in the bridgetown-core test suite related to `pager`. I would love to expand more on this PR but need maybe a little more guidance.
Addresses #145
> feat: alias pager to paginator

- bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
- bridgetown-core/test/source/src/page_using_erb.erb
- bridgetown-core/test/test_erb.rb
- bridgetown-website/src/_docs/erb-and-beyond.md
- bridgetown-website/src/_docs/liquid/tags.md
> Add Class Map helper and usage info in docs

- bridgetown-builder/test/test_helpers_dsl.rb
- bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
- bridgetown-website/src/_docs/plugins/helpers.md
> Add view reference to template helpers object

- bridgetown-builder/lib/bridgetown-builder/document.rb
- bridgetown-builder/lib/bridgetown-builder/plugin.rb
- bridgetown-core/benchmark/indifferent-access.rb
- bridgetown-core/bridgetown-core.gemspec
- bridgetown-core/lib/bridgetown-core.rb
- bridgetown-core/lib/bridgetown-core/concerns/site/content.rb
- bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
- bridgetown-core/lib/bridgetown-core/concerns/validatable.rb
- bridgetown-core/lib/bridgetown-core/configuration.rb
- bridgetown-core/lib/bridgetown-core/document.rb
- bridgetown-core/lib/bridgetown-core/readers/data_reader.rb
- bridgetown-core/lib/bridgetown-core/readers/defaults_reader.rb
- bridgetown-core/lib/bridgetown-core/utils/ruby_exec.rb
- bridgetown-core/test/test_configuration.rb
- bridgetown-core/test/test_data_reader.rb
- bridgetown-website/src/_docs/erb-and-beyond.md
- bridgetown-website/src/_docs/front-matter.md
Closes #144 
```
site.data.authors.jared.website
=> "https://jaredwhite.com"
```
That's a thing of beauty!
> Use HashWithDotAccess::Hash for all data/config hashes

- bridgetown-website/src/_docs/plugins/filters.md
Fixed 2 occurrences of a wrong class syntax.
> Fix filter doc

- bridgetown-core/lib/bridgetown-core/filters.rb
- bridgetown-core/lib/bridgetown-core/helpers.rb
- bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
- bridgetown-core/lib/bridgetown-core/utils.rb
- bridgetown-core/test/test_erb.rb
- bridgetown-core/test/test_ruby_helpers.rb
- bridgetown-website/src/_docs/erb-and-beyond.md
> Add link/url_for and link_to helpers

- bridgetown-builder/lib/bridgetown-builder/dsl/liquid.rb
- bridgetown-builder/test/test_filters_dsl.rb
- bridgetown-website/src/_docs/plugins/filters.md
> Add filters_scope option to liquid_filter DSL

- bridgetown-core/lib/site_template/README.md
Closes #87 
Co-authored-by: Andrew Mason <andrewmcodes@protonmail.com>
> Add README to new site template

- bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
- bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
There is a plugin in the works to add a compatibility layer for [ViewComponent](https://viewcomponent.org). 🤯
This fixes/enhances a few low-level template pieces to support that plugin's behavior.
Much more information/documentation/demos forthcoming. 😁
> Support required for upcoming ViewComponent plugin

- README.md
- bridgetown-website/src/_docs/bundled-configurations.md
This is a documentation change. (fix)
> Fix bundled configurations docs typo

- README.md
The contributors table in the main Readme was broken. Just fixing that.
> Fix contributors section layout in readme

- .github/workflows/build.yml
This is a 🙋 feature or enhancement (for CI)
I was bored and looking at source code while this CI test suite runs and noticed we werent using caching native to ruby/setup-ruby!
> update gh actions to use native ruby caching.

- bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
- bridgetown-core/lib/bridgetown-core/converters/liquid_templates.rb
- bridgetown-core/lib/bridgetown-core/site.rb
Not a real PR — test test test!
> test change to try out Render PR previews

- bridgetown-core/lib/bridgetown-core/drops/relations_drop.rb
- bridgetown-core/lib/bridgetown-core/drops/resource_drop.rb
- bridgetown-core/lib/bridgetown-core/resource/base.rb
- bridgetown-core/lib/bridgetown-core/resource/relations.rb
- bridgetown-core/test/resources/src/_noodles/ramen.liquid
- bridgetown-core/test/resources/src/_pages/_ignore_me/noodles.liquid
- bridgetown-core/test/resources/src/_posts/pass-thru/2019-09-09-bløg Pöst.md
- bridgetown-core/test/test_relations.rb
- bridgetown-website/Gemfile
- bridgetown-website/src/_docs/resources.md
Resolves #260
(wow, this ended up easier to implement than I imagined!)
> Relations for resources (belongs_to, has_many, etc.)

- bridgetown-website/src/_docs/bundled-configurations.md
- bridgetown-website/src/_docs/testing.md
Updates the testing page to demonstrate using a bundled configuration rather than an automation
Resolves https://github.com/bridgetownrb/bridgetown/issues/309
> Link testing and configurations docs pages

- bridgetown-core/lib/bridgetown-core/component.rb
Through benchmarking a site with 10,000 posts, I found a major need for optimizing the initialization of component template objects. This PR will knock several seconds off a large site build compared to the most recent 0.21 beta! 🎉
> Add memoization to cache templates in `Bridgetown::Component`

- bridgetown-core/test/helper.rb
- bridgetown-core/test/test_apply_command.rb
- bridgetown-core/test/test_new_command.rb
- bridgetown-core/test/test_webpack_command.rb
Starting this PR to investigate crashes. See #318
> Test suite troubleshooting

- bridgetown-website/src/_docs/components/ruby.md
This is a 🔦 documentation change
Adds documentation on how the ActionView helpers allowlist works.
Fixes bridgetownrb/bridgetown-view-component#1
> docs(components): Document how the ActionView helpers allowlist works

- bridgetown-core/lib/bridgetown-core/configurations/tailwindcss/postcss.config.js
The stage 3 setup will remove all Tailwind breakpoints from the exported output.
> Update postcss.config.js for the Tailwind bundled configuration

- bridgetown-website/src/_docs/index.md
- I read the Project Goals and Future Roadmap pages at: https://bridgetownrb.com/docs/philosophy/
- I read the Code of Conduct: https://github.com/bridgetownrb/bridgetown/blob/master/CODE_OF_CONDUCT.md
- I've adjusted the documentation (if it's a feature or enhancement)
Indicate instructions also available for Fedora Linux
Fedora had been added in https://github.com/bridgetownrb/bridgetown/pull/209 and https://github.com/bridgetownrb/bridgetown/pull/210
> Add Fedora Linux

- bridgetown-core/lib/bridgetown-core/frontmatter_defaults.rb
- bridgetown-core/lib/bridgetown-core/resource/base.rb
- bridgetown-core/test/resources/src/_posts/_defaults.yml
- bridgetown-core/test/test_resource.rb
- bridgetown-paginate/lib/bridgetown-paginate/pagination_model.rb
- bridgetown-paginate/lib/bridgetown-paginate/utils.rb
> Resource: switch from default proc to preemptive defaults

- bridgetown-core/lib/bridgetown-core/reader.rb
> Ensure the data collection is read first

- bridgetown-core/lib/site_template/start.js
> fix small space on start.js

- bridgetown-website/src/_posts/2021/2021-09-02-roadmap-to-1.0.md
> Add draft blog post with the Roadmap to 1.0

- bridgetown-core/lib/bridgetown-core/helpers.rb
- bridgetown-core/lib/bridgetown-core/tags/link.rb
> Improve resource engine compatibility in `link` tag and `url_for` helper

- bridgetown-website/src/_pages/plugins.liquid
At least can save one click for user
> Show archive state for plugins.

- bridgetown-core/bin/bridgetown
> support long version form.

- bridgetown-core/lib/bridgetown-core/commands/plugins.rb
Removed an extra space in the terminal output!
> Remove extra space

- bridgetown-core/lib/bridgetown-core/configurations/render/render.yaml.erb
Resolves https://github.com/bridgetownrb/bridgetown/issues/459
> Add BRIDGETOWN_ENV to render config

- bridgetown-website/src/_docs/deployment.md
Tested on deploy the bridgetown-website.
> Add a nginx section in deployment

- README.md
Shamelessly adding myself to the sponsor list 😅
> Update Sponsor list within README.md

- bridgetown-core/lib/bridgetown-core/commands/esbuild/esbuild.config.js
- bridgetown-core/lib/bridgetown-core/rack/roda.rb
- bridgetown-core/lib/bridgetown-core/rack/routes.rb
- bridgetown-core/lib/bridgetown-core/utils.rb
- bridgetown-core/lib/site_template/TEMPLATES/erb/_components/shared/navbar.erb
- bridgetown-core/lib/site_template/TEMPLATES/liquid/_components/navbar.liquid
- bridgetown-core/lib/site_template/TEMPLATES/serbea/_components/shared/navbar.serb
> Fix `base_path` issues with Roda and site templates

- bridgetown-website/src/_pages/community.md
Added knowledgebase.redwebtigers.com website to 'People are using Bridgetown to build amazing things!' in community.md
> Added knowledgebase.redwebtigers.com to community.md

- bridgetown-website/src/_posts/2020/2020-05-07-postcss-tailwind-plugins-oh-my.md
> Fix link to https://andrewm.codes

- bridgetown-website/src/_pages/community.md
This is a 🔦 content change on the bridgetown website.
Added [apacagencies.com](https://www.apacagencies.com) to the "Bridgetown in the Wild" section of the Community page on Bridgetown Website.
apacagencies.com websites uses prototype pages, custom taxonomies, seo and cloudinary plugins and turbo integration.
> added apacagencies.com to community.md

- bridgetown-website/src/_docs/front-matter.md
> fix grammar in doc

- bridgetown-core/bridgetown-core.gemspec
- bridgetown-core/lib/bridgetown-core/rack/roda.rb
- bridgetown-core/test/ssr/server/routes/ooh_json.rb
Ha, I don't get to use the `dependencies` label very often! ;-)
> Switch from rack-indifferent to Roda's indifferent_params plugin

- bridgetown-core/lib/bridgetown-core/rack/roda.rb
- bridgetown-core/test/ssr/server/roda_app.rb
- bridgetown-core/test/ssr/server/routes/kello.rb
- bridgetown-core/test/ssr/server/routes/redirecting.rb
- bridgetown-core/test/test_ssr.rb
- bridgetown-website/src/_docs/routes.md
> Provide URL helpers to Roda

- bridgetown-website/src/_docs/deployment.md
Updates the GitLab Pages section to change "fie" to "file" to refer to
the .yml file needed for deploying to GitLab pages.
[Deployed Documentation](https://www.bridgetownrb.com/docs/deployment#gitlab-pages)
> Fix typo in deployment docs

- bridgetown-website/frontend/javascript/index.js.rb
- bridgetown-website/package.json
- bridgetown-website/src/_components/post_card.serb
- bridgetown-website/src/_docs/components.md
- bridgetown-website/src/_docs/template-engines.md
- bridgetown-website/src/_docs/template-engines/liquid.md
- bridgetown-website/src/_layouts/docs.serb
- bridgetown-website/src/_layouts/post.serb
- bridgetown-website/src/_pages/authors/[author].serb
- bridgetown-website/src/_pages/blog.serb
- bridgetown-website/src/_pages/blog/[category].serb
- bridgetown-website/src/_pages/index.md
- bridgetown-website/src/_partials/_footer.serb
- bridgetown-website/yarn.lock
* Lock esbuild to version 0.14.54
* Bump @shoelace-style/shoelace version to 2.0.0-beta.80
Bump the rest of the js package and human visual check result in [staging](https://bridgetown.redwoodjs.cn), seems OK.
> Bump to @shoelace-style/shoelace version to 2.0.0-beta.80

- bridgetown-website/src/_docs/installation/upgrade.md
- bridgetown-website/src/_posts/2022/2022-10-10-1.2-bonny-scope-next-level.md
Don't merge until Upgrade Guide is finished
> draft post about the 1.2 beta

- bridgetown-core/lib/bridgetown-core/drops/drop.rb
- bridgetown-core/lib/bridgetown-core/utils.rb
This is a 🔦 tiny naming change.
I have the feeling that it's called [mergeable](https://en.wiktionary.org/wiki/mergeable) but I'm not a native speaker so I might be wrong.
> typo: mergable => mergeable

- bridgetown-core/lib/bridgetown-core/tasks/bridgetown_tasks.rake
> Remove `bundle exec` from frontend process invocation

- bridgetown-website/src/_docs/collections.md
> Fix typo in collections.md

- bridgetown-core/lib/bridgetown-core/configuration.rb
- bridgetown-core/lib/bridgetown-core/watcher.rb
- bridgetown-website/src/_docs/configuration/options.md
> Provide an option for the file watcher to watch additional paths

- bridgetown-routes/lib/bridgetown-routes/manifest.rb
- bridgetown-routes/test/ssr/src/_routes/nested/[slug].erb
- bridgetown-routes/test/ssr/src/_routes/nested/index.erb
- bridgetown-routes/test/test_routes.rb
> fix: dynamic route sorting

- bridgetown-core/lib/bridgetown-core/drops/static_file_drop.rb
- bridgetown-core/lib/bridgetown-core/static_file.rb
- bridgetown-website/src/_docs/static-files.md
Extracted from my blog and cleaned up.
> Add some DX improvements to `StaticFile`

- bridgetown-core/lib/bridgetown-core/commands/plugins.rb
> Fix a minor typo in the plugins command

- bridgetown-website/frontend/styles/global.css
- bridgetown-website/frontend/styles/theme-dark.css
This PR simply has color enhancements for syntax in dark mode. 
We wanted to make sure colors met standards for accessibility but also remained aesthetically pleasing.
> Update syntax colors on dark mode

- Gemfile
- bridgetown-builder/lib/bridgetown-builder/dsl/inspectors.rb
- bridgetown-builder/test/test_inspectors.rb
- bridgetown-core/lib/site_template/Gemfile.erb
- bridgetown-core/test/helper.rb
- bridgetown-website/Gemfile
- bridgetown-website/bridgetown.config.yml
- bridgetown-website/frontend/javascript/index.js.rb
- bridgetown-website/src/_docs/plugins/inspectors.md
- bridgetown-website/src/_pages/index.md
- bridgetown-website/src/_pages/plugins.serb
> Add support for Nokolexbor & Puma 6.x

- bridgetown-website/src/_docs/deployment.md
Bridgetown no longer uses Webpack by default. Instead, run the umbrella command `bridgetown deploy` as [mentioned in the documentation](https://www.bridgetownrb.com/docs/deployment).
You can see an up & running example on my personal blog repository:
https://gitlab.com/strigocc/code/-/blob/main/.gitlab-ci.yml
> doc: update gitlab pages deploy configuration

- bridgetown-core/lib/bridgetown-core/commands/esbuild/jsconfig.json
- bridgetown-core/lib/site_template/postcss.config.js.erb
* Remove trailing whitespace from template resource
* These whitespace will cause diff by editor's auto-formatted save
* None
> Remove trailing whitespace from template resource

- bridgetown-website/src/_posts/2020/2020-05-07-postcss-tailwind-plugins-oh-my.md
> Add notice to Tailwind CSS blog post about bundled configuration

- bridgetown-website/src/_docs/routes.md
- bridgetown-website/src/_posts/2021/2021-10-24-era-of-bridgetown-v1.md
> Fix spelling of cuprite

- bridgetown-website/src/_pages/community.md
This PR adds Kaigi on Rails website to the list in the community page.
I just noticed the list, and since we use Bridgetown this year (thank you!), I thought it's worth adding it.
> [website] Add Kaigi on Rails website to the list

- bridgetown-core/lib/bridgetown-core/concerns/site/fast_refreshable.rb
- bridgetown-website/src/_docs/configuration/initializers.md
- bridgetown-website/src/_docs/installation/upgrade.md
> Fix fast refresh not working for Liquid templates

- bridgetown-website/src/_docs/installation/upgrade.md
Minor docs improvement in the upgrade guide.
> Add note to update the package manager in the rakefile

- bridgetown-core/lib/roda/plugins/bridgetown_server.rb
> Fix regression in `base_path` support

- CHANGELOG.md
- bridgetown-core/lib/bridgetown-core/configurations/gh-pages/gh-pages.yml
Updates gh-pages bundled config
fixes #919
> fix: update `gh_pages` bundled config

- .yardopts
- bridgetown-core/lib/bridgetown-core.rb
Resolves #961 
(mostly, there may be a few bits we want to exclude after further review, but this is a lot of it)
> Add some file excludes for YARDoc generation

- bridgetown-core/lib/bridgetown-core/collection.rb
> Better `inspect` output for `Bridgetown::Collection`

- bridgetown-core/lib/bridgetown-core/front_matter/loaders/ruby.rb
- bridgetown-core/lib/bridgetown-core/front_matter/loaders/yaml.rb
> fix: add carriage return to front matter regex

- bridgetown-core/lib/site_template/config/initializers.rb
- bridgetown-routes/lib/bridgetown-routes.rb
- bridgetown-routes/test/ssr/config/initializers.rb
- bridgetown-routes/test/ssr/src/_routes/howdy.erb
- bridgetown-routes/test/test_routes.rb
- bridgetown-website/src/_docs/routes.md
> fix: routes plugin should init ssr with sessions: true by default

- bridgetown-core/lib/bridgetown-core/tasks/bridgetown_tasks.rake
> Change the color of the Frontend log statements to blue
