CHANGELOG.md
bridgetown-core/features/step_definitions.rb
bridgetown-core/features/support/helpers.rb
bridgetown-core/features/webpack_path_tag.feature
bridgetown-core/lib/bridgetown-core/tags/webpack_path.rb
bridgetown-core/lib/bridgetown-core/version.rb
bridgetown-core/lib/bridgetown-core/watcher.rb
bridgetown-core/lib/site_template/.gitignore
bridgetown-core/lib/site_template/package.json
bridgetown-core/lib/site_template/src/_includes/head.html
bridgetown-core/lib/site_template/webpack.config.js
bridgetown-website/.gitignore
bridgetown-website/frontend/fonts/inter.css
bridgetown-website/frontend/javascript/index.js
bridgetown-website/package.json
bridgetown-website/src/_includes/head.html
bridgetown-website/webpack.config.js
bridgetown-website/yarn.lock

This PR adds new Liquid tags for use in the HTML head to load the hashed output files from the Webpack bundler. So now you can simply add:
```html
<link rel="stylesheet" href="{% webpack_path css %}" />
<script src="{% webpack_path js %}" defer></script>
```
And the tag will open the manifest saved in `.bridgetown-webpack/manifest.json` and locate the proper hashed asset (aka `/_bridgetown/static/css/all.1e4140d3a350deac0198.css`).

First pass at Webpack manifest support for JS/CSS output bundles

---

bridgetown-core/lib/bridgetown-core/plugin_manager.rb
bridgetown-website/src/_docs/frontend-assets.md
bridgetown-website/src/_docs/plugins.md
bridgetown-website/src/_docs/plugins/gems-and-webpack.md
bridgetown-website/src/_posts/2020/2020-04-17-time-to-visit-bridgetown.md
bridgetown-website/src/about.md

This lets you use an NPM package which will get installed and run alongside your plugin. The way it works is, from the docs:
----
Let's assume you've been building an awesome plugin called, unsurprisingly,
`MyAwesomePlugin`. In your `my-awesome-plugin.gemspec` file, all you need to do is
add the `yarn-add` metadata matching the NPM package name and keeping the version
the same as the Gem version:
```ruby
spec.metadata = { "yarn-add" => "my-awesome-plugin@#{MyAwesomePlugin::VERSION}" }
```
With that bit of metadata, Bridgetown will know always to look for that package in
the users' `package.json` file when they load Bridgetown, and it will trigger a
`yarn add` command if the package and exact version number isn't present.

Provide a yarn add step for gem plugins with the relevant metadata when they get loaded

---

.rubocop.yml
bridgetown-core/features/post_excerpts.feature
bridgetown-core/lib/bridgetown-core/commands/new.rb
bridgetown-core/lib/site_template/.gitignore

I'm surprised this wasn't already happening, so this PR adds a `git init` step after creating the new site folder. If the command fails (i.e. git isn't present on the system), it doesn't throw an error. Thanks to Rails' PR history for highlighting that potential gotcha. 😄
Fixes #16

Add a git init step to bridgetown new command

---

.rubocop.yml
CHANGELOG.md
README.md
bridgetown-core/features/post_excerpts.feature
bridgetown-core/lib/bridgetown-core/commands/new.rb
bridgetown-core/lib/bridgetown-core/generators/prototype_generator.rb
bridgetown-core/lib/site_template/.gitignore
bridgetown-paginate/lib/bridgetown-paginate.rb
bridgetown-paginate/lib/bridgetown-paginate/defaults.rb
bridgetown-paginate/lib/bridgetown-paginate/hooks.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_generator.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_indexer.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_model.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_page.rb
bridgetown-paginate/lib/bridgetown-paginate/paginator.rb
bridgetown-paginate/lib/bridgetown-paginate/utils.rb
bridgetown-website/src/_docs/plugins.md
bridgetown-website/src/_docs/prototype-pages.md

Just what the title says. Lets you easily utilize the permalink variable on prototype pages, aka `/path/to/:term/and/beyond`. _Inspired by [use cases like this](https://annualbeta.com/blog/dynamic-social-sharing-images-with-eleventy/)…_
Documentation added.
Also addressed some performance issues mentioned in #15 with Pagination, so hopefully this is now in a decent place. (Still need to test sites with many thousands of documents in multiple collections, etc.)

Add permalink support to Prototype pages

---

bridgetown-core/lib/site_template/webpack.config.js

I may be _completely_ crazy, but I like the indented form of sass and the `.sass` file extension.
This little tweak (ripped from the [sass-loader readme](https://github.com/webpack-contrib/sass-loader)) makes it so webpack supports both out of the box.

Update sass-loader webpack config to support .sass

---

Gemfile
bridgetown-core/bridgetown-core.gemspec
bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/test/test_commands_serve.rb
bridgetown-core/test/test_commands_serve_servlet.rb

Add Faraday to the default set of gems that get installed with Bridgetown. Now site builders and gem plugins can all expect a modern Ruby HTTP client with all the bells and whistles ready to go out of the box.
Closes #19

Add Faraday to default gems

---

bridgetown-core/lib/bridgetown-core/liquid_renderer.rb
bridgetown-core/lib/bridgetown-core/liquid_renderer/file_system.rb

I ran across a `US-ASCII` encoding bug when using a remote SSH session that was incorrectly configured (aka not indicating a `UTF-8` shell) in conjunction with Bridgetown's new support for Liquid's `render` tag. It was preventing the site from building.
This resolves that error.

Honor the configured site encoding when loading Liquid components

---

.github/workflows/build.yml

Adds caching for bundled gems to improve test speed on subsequent runs for [GitHub Actions](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows)
I noticed that you are not running the tests or linters for pull requests except on master. I didn't add this in because it would be super quick to add and I figured there may be a reason but I have found [this](https://github.com/gitcoinco/code_fund_ads/blob/master/.github/workflows/standardrb.yml#L3) setup to be ideal as sometimes people will merge stuff into their own branches and tests would not run if they were not pointing at master. 
N/A

add bundler cache to the build GH action to improve test speed

---

bridgetown-core/lib/site_template/src/_includes/navbar.html
bridgetown-core/lib/site_template/src/posts.md

__I did some looking and I did not find where you were testing this. It is totally possible, if not probable, that I just missed it so would appreciate you pointing me in that direction if I did indeed just overlook it :smile:__
__I did some looking and I do not see it documented what get's generated from the build command__
When generating a new bridgetown site, it is not immediately clear how to get to your posts. I attempted a few ways to navigate there, but since I do not have prior experience with Jekyll, I was a little lost. This commit adds a posts page so that feature newbies, like myself, can quickly see their posts, and not have to try and spend time figuring it out.
Not related to any currently open issues, but may help prevent some from …

add a posts page to the new site template

---

bridgetown-core/lib/bridgetown-core/filters.rb
bridgetown-core/lib/bridgetown-core/utils.rb
bridgetown-core/test/test_filters.rb
bridgetown-website/src/_data/bridgetown_filters.yml

Like the docs say: a Liquid filter to transform a lowercase string, slug, or identifier string into a capitalized title. Uses the already present `Utils.titleize_slug` method.
input: `{{ "to-kill-a-mockingbird" | titleize }}`
output: `To Kill A Mockingbird`

Add titleize Liquid filter

---

bridgetown-core/lib/bridgetown-core/commands/apply.rb
bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb
bridgetown-core/test/test_apply_command.rb

- I've added tests (if it's a bug, feature or enhancement)
- The test suite passes locally (run `script/cibuild` to verify this)
My pull request allow you to use a branch for the command "apply"
It transforms the Github url to one that allows the use of a branch
IE: 
`https://github.com/bridgetownrb/bridgetown/tree/automations`
turns to
`https://raw.githubusercontent.com/bridgetownrb/bridgetown/automations/bridgetown.automation.rb`
Fixes #65

Fix for GitHub branch URLs in automations (0.15)

---

bridgetown-website/Gemfile
bridgetown-website/package.json
bridgetown-website/plugins/test_output.rb
bridgetown-website/src/_docs/deployment.md
bridgetown-website/src/_docs/plugins/hooks.md
bridgetown-website/src/_docs/testing.md
bridgetown-website/test/helper.rb
bridgetown-website/test/test_blog.rb
bridgetown-website/test/test_documentation.rb
bridgetown-website/test/test_navbar.rb

Adding a Minitest/Nokogiri test suite via a `post_write` hook to the Bridgetown website. Initial commit here should fail, as I want to test how Netlify handles the build. It should give us a red X, and if I fix the test we'll get a green checkmark.
(This is in reference to #48)

Website experiment with test suite

---

bridgetown-website/frontend/javascript/index.js
bridgetown-website/frontend/styles/content.scss

The animations when navigating between pages on [the documentation](https://www.bridgetownrb.com/docs/core-concepts) are giving me a headache.
I have reduced motion enabled so expect less animation. This removes the animation for users who have "Reduce Motion" checked.
I've not opened an issue, I created a PR to experiment with solution & get feedback.

Reducing animation for users who prefer reduced motion

---

bridgetown-website/src/_docs/content/pagination.md

Update pagination documentation to include information on how to use the `per_page` key.
I do not currently see a place in the docs that we call out how to set the amount of paginated items per page. I had to go look in the source code, so this addition adds a little blurb about the `per_page` key to the pagination docs to make it easier to find.

Update pagination documentation

---

bridgetown-core/lib/bridgetown-core/tags/class_map.rb
bridgetown-core/test/test_tags.rb

Rough implementation, appears to pass normal use cases. Due to how this is implemented, only variables can be given as values. If the variable is false, nil, etc, it will not display in the output. Let me know if there's any questions.
Adds a `{% class_map %}` tag as discussed in #86. 
Adds testing for the `class_map` tag

feat(tags): Adding a class_map tag

---

bridgetown-core/features/webpack_path_tag.feature
bridgetown-core/lib/bridgetown-core/errors.rb
bridgetown-core/lib/bridgetown-core/tags/webpack_path.rb

This pull request provides better error handling for Webpack manifest file issues. Also adds YARD documentation for webpack_path.
I have added additional tests to the feature spec for `webpack_path` as well as tested locally.
Here is what the new error log looks like:
```bash
[Bridgetown]
[Bridgetown]           There was an error parsing your css files.
[Bridgetown]           Please check your css for any errors.
[Bridgetown]
[Bridgetown]
[Bridgetown] /home/krog/.gem/ruby/2.6.3/gems/bridgetown-core-0.15.0/lib/bridgetown-core/tags/webpack_path.rb:54:in `parse_manifest_file'
[Bridgetown] /home/krog/.gem/ruby/2.6.3/gems/bridgetown-core-0.15.0/lib/bridgetown-core/tags/webpack_path.rb:38:in `render'
[Bridgetown] …
```

Feat: webpack manifest errors

---

bridgetown-core/features/webpack_path_tag.feature
bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
bridgetown-core/lib/bridgetown-core/tags/webpack_path.rb
bridgetown-core/lib/bridgetown-core/utils.rb

Hey @ParamagicDev, I relocated the bulk of the code that parses the manifest to the Utils module so we can use it from ERB/etc. as well. I also changed the behavior so it doesn't actually trigger any runtime errors and always lets the site build…I think there must have been a communication mixup before and I thought that's how it was already working. Anyway, if you could give this a quick looksee before merge, I'd appreciate it!
(Also fixed an issue with using Liquid filters from ERB…had to add duck-typing for a `@context` ivar so the filters could access the current `site` object).

Move Webpack parsing to Utils, enable for ERB templates

---

bridgetown-website/Gemfile
bridgetown-website/bridgetown.config.yml
bridgetown-website/plugins/builders/tags.rb
bridgetown-website/src/_components/shared/footer.liquid
bridgetown-website/src/_components/shared/navbar.liquid
bridgetown-website/src/_layouts/home.html
bridgetown-website/src/inverse_logo.html

- Adds the [bridgetown-inline-svg](https://github.com/andrewmcodes/bridgetown-inline-svg) plugin for easier handling and inline of SVG assets on the website.
- Removes `insert_svg` tag that was created to handle this previously
@jaredcwhite mentioned he wanted to do this so I decided to save him the work! 💪

Replace 'insert_svg' with 'bridgetown-inline-svg' plugin on website

---

bridgetown-website/src/_posts/2020/2020-06-18-major-workflow-advances-in-0.15-overlook.md
bridgetown-website/src/index.md

This add the [`loading="lazy"`](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#Images_and_iframes) method to the iframes, which means the browser won't load the iframe until the viewport is close to showing that iframe. It also adds a `title` attribute to improve accessibility.
I measured via https://web.dev/measure/ 
**Current Lighthouse**
**Review App Lighthouse**
As you can see it's a minor improvement, though hard to know if it's just lighthouse hitting a different URL & caching differently (The SEO change is due to the review apps being no-index).
**What's happening?**
If you look kind of close at the network order, it's loading the YouTube iFrame after the page has loaded (after the fonts). …

feat: Lazy loading iframes & adding title attribute to them

---

bridgetown-website/src/_components/content/news_item.liquid
bridgetown-website/src/_components/shared/footer.liquid
bridgetown-website/src/plugins.html
bridgetown-website/test/test_blog.rb

This lazy loads of images which are not in the initial viewport of the homepage. It's the same approach I used on the iFrame & it looks super effective on https://web.dev/measure/
Only catch with this PR is you can see the images loading in if you scroll fast enough.
Continuing on from https://github.com/bridgetownrb/bridgetown/pull/108 which was inspired by https://github.com/bridgetownrb/bridgetown/issues/103

Adding loading="lazy" to images near footer

---

bridgetown-website/src/_components/shared/footer.liquid
bridgetown-website/src/_components/shared/navbar.liquid
bridgetown-website/src/_data/bridgetown_filters.yml
bridgetown-website/src/_data/bridgetown_variables.yml
bridgetown-website/src/_docs/components.md
bridgetown-website/src/_docs/configuration/incremental-regeneration.md
bridgetown-website/src/_docs/configuration/options.md
bridgetown-website/src/_docs/datafiles.md
bridgetown-website/src/_docs/front-matter.md
bridgetown-website/src/authors/author.html
bridgetown-website/src/plugins.html

https://github.com/bridgetownrb/bridgetown/pull/109 Pulled from here. This adds `rel="noopener"` to external HTTP links. It's one of the quick wins to help improve the lighthouse score.
This solves the "Links to cross-origin destinations are unsafe" best practice. 
When I run https://web.dev/measure/ against the review app, that suggestion is now gone :)
https://github.com/bridgetownrb/bridgetown/issues/103

Adding rel="noopener" to external links

---

bridgetown-core/lib/bridgetown-core/plugin_manager.rb

This gets the action working again so you can do this in an automation:
```ruby
add_bridgetown_plugin :bulmatown
add_yarn_for_gem :bulmatown
```
I'd add tests but almost everything else in this flow is already tested and this part is very specific to gem specifications so it'd require mocking the gem specs…so will hold off for the time being.

Fix the "add_yarn_for_gem" action

---

bridgetown-website/src/_docs/deployment.md

This PR adds instructions to the deployment section in the guides on how to configure your Bridgetown project to deploy it to a Dokku server. The same instructions may work as well on Heroku, but I haven't tested it.
The guide is a bit longer than the rest of the instructions on that page and I wasn't sure if it needed a separate page or not. Please let me know if I need to change the wording/writing style or put it in a separate page.

Add Dokku installation instructions to the guides section in the website

---

bridgetown-website/src/_docs/plugins/filters.md

Fix filter plugin doc

---

bridgetown-core/lib/bridgetown-core/concerns/site/localizable.rb
bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/lib/bridgetown-core/drops/site_drop.rb
bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
bridgetown-core/lib/bridgetown-core/site.rb
bridgetown-core/lib/bridgetown-core/tags/t.rb

Partially addresses #49 
This PR adds two new concepts to Bridgetown:
* Available locales. You can now add an `available_locales` key to your config to list one or more locales (en, fr, zh, etc.) OOTB it's "en". Bridgetown will configure the I18n gem with those locales and to look for YAML files in `src/_locales`, so you can add translation files just like you would in a Rails app.
* Current locale. A site always has a current locale, configured either by the `BRIDGETOWN_LOCALE` environment variable if present or the `default_locale` config key. You can access this value in templates via `site.locale`, and in Ruby code (plugins, etc.) you can switch the current site locale via `site.locale = :de`.
It also adds a `t` helper for ERB/etc. templates and a `t` Liquid tag. The Liquid tag is …

First pass at implementing site locales and translations

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
bridgetown-core/lib/bridgetown-core/frontmatter_defaults.rb
bridgetown-core/lib/bridgetown-core/reader.rb
bridgetown-core/lib/bridgetown-core/readers/collection_reader.rb
bridgetown-core/lib/bridgetown-core/readers/data_reader.rb
bridgetown-core/lib/bridgetown-core/readers/defaults_reader.rb
bridgetown-core/lib/bridgetown-core/readers/layout_reader.rb
bridgetown-core/lib/bridgetown-core/readers/page_reader.rb
bridgetown-core/lib/bridgetown-core/readers/post_reader.rb
bridgetown-core/lib/bridgetown-core/readers/static_file_reader.rb
bridgetown-core/test/source/src/_posts/_defaults.yml
bridgetown-core/test/source/src/_posts/es/_defaults.yml
bridgetown-core/test/source/src/_posts/es/further/2020-09-10-further-nested.md
bridgetown-core/test/test_defaults_reader.rb
bridgetown-core/test/test_filters.rb
bridgetown-core/test/test_front_matter_defaults.rb
bridgetown-core/test/test_generated_site.rb
bridgetown-core/test/test_site.rb
bridgetown-website/bridgetown.config.yml
bridgetown-website/src/_defaults.yml
bridgetown-website/src/_docs/_defaults.yml
bridgetown-website/src/_posts/_defaults.yml
bridgetown-website/src/_posts/drafts/_defaults.yml

Related to #50 
This PR provides the ability to put a `_defaults.yml/yaml/json` file(s) anywhere in the source tree, which will then cause a "data cascade" — aka pages/documents will pull their front matter defaults from one or more defaults files in the tree with subfolders potentially overriding values from their parents.
While this isn't a 100% replacement for the previous defaults config syntax, as you can see here with the changes made to the Bridgetown website, it very well can be a wholesale replacement.
Still needs documentation/tests.

Process data cascade for folder-based frontmatter defaults

---

bridgetown-website/src/_docs/plugins/external-apis.md

- I've adjusted the documentation (if it's a feature or enhancement)
Added documentation on how to use GraphQL via Graphtown
fixes #137

docs: add graphtown to the documentation

---

bridgetown-core/lib/bridgetown-core/filters.rb
bridgetown-core/test/test_filters.rb
bridgetown-website/src/_data/bridgetown_filters.yml

Close #129.
I thought about making the filter output a word like "minute" or "minutes" along with the number, but then you run into issues like localization or capitalization or whatever, so I figured just outputting a number is good enough. Let the template handle additional wording.

Add reading_time filter/helper

---

bridgetown-core/features/permalinks.feature
bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/lib/bridgetown-core/page.rb
bridgetown-core/test/test_entry_filter.rb
bridgetown-website/src/_docs/pages.md
bridgetown-website/src/_docs/structure.md

Fixes #57
This was a surprisingly non-trivial change. I've seen some folks over on the Jekyll side create a collection called `pages` and use that, but getting the native page reader and final permalinks to support a `_pages` folder required a bit of tweaking. I'm on the fence if this should be the "default" pattern now (aka update the site template for `bridgetown new` to use a `_pages` folder), but at least it will be fully supported going forward.

Support a _pages folder in the source tree

---

bridgetown-core/lib/bridgetown-core/collection.rb
bridgetown-core/lib/bridgetown-core/concerns/site/content.rb
bridgetown-core/lib/bridgetown-core/concerns/site/writable.rb
bridgetown-core/lib/bridgetown-core/drops/site_drop.rb
bridgetown-core/lib/bridgetown-core/reader.rb
bridgetown-core/lib/bridgetown-core/readers/post_reader.rb
bridgetown-core/lib/bridgetown-core/site.rb
bridgetown-core/test/test_document.rb
bridgetown-core/test/test_site.rb
bridgetown-website/src/_data/bridgetown_variables.yml

In researching a fix for #161, I discovered that static files loaded within a collection would be added to the `site.documents` array! Furthermore, they *wouldn't* be added to the `site.static_files` array. I don't know about you, but to me that seems exactly backwards from what you would expect. 🤪
So this PR fixes that — and in addition, there is now a `site.contents` array which includes _all_ pages and documents in the site. Every single one. So no more having to concatenate `site.pages` and `site.documents`, or loop through each separately…unless you really want to.

Site documents array should exclude static files

---

bridgetown-core/.yardopts
bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
bridgetown-core/lib/bridgetown-core/concerns/site/content.rb
bridgetown-core/lib/bridgetown-core/concerns/site/extensible.rb
bridgetown-core/lib/bridgetown-core/concerns/site/localizable.rb
bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
bridgetown-core/lib/bridgetown-core/concerns/site/renderable.rb
bridgetown-core/lib/bridgetown-core/concerns/site/writable.rb
bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/lib/bridgetown-core/generators/prototype_generator.rb
bridgetown-core/lib/bridgetown-core/log_writer.rb
bridgetown-core/lib/bridgetown-core/site.rb
bridgetown-website/package.json
bridgetown-website/yarn.lock

Just some low-level improvements and a lot of tweaks to the YARD docs.

chore: Prototype pages optimizations and improvements to YARD docs

---

.github/workflows/build.yml

I hit an issue on Ruby 3 (that I will open in a sec), and was hoping that GitHub may provide access to use it but I see not. I am going to try a few other things but I think some matrix testing would help make sure that people on lower ruby versions aren't affected in changes.
1min

build: add matrix testing for Ruby

---

bridgetown-core/lib/bridgetown-core/filters.rb
bridgetown-core/test/test_filters.rb
bridgetown-website/src/_data/bridgetown_filters.yml

This PR introduces a simple `obfuscate_link` filter to prevent bots from sending emails etc.
The implementation takes the simplest path possible, reversing the link text and using CSS reading-direction style attributes to display it correctly.
The link href is replaced by `obfuscated` and the original target is restored on mouseover or focus (touch friendly). 
Closes #166

Obfuscate link filter

---

bridgetown-core/features/rendering.feature
bridgetown-core/lib/bridgetown-core/concerns/layout_placeable.rb
bridgetown-website/src/_docs/front-matter.md
bridgetown-website/src/_docs/layouts.md

Fixes #159 
Previously only `layout: none` would reliably switch off layout processing for a document even in the presence of front matter defaults. This PR allows `layout: false` as well.

False value supported for no layouts

---

.rubocop.yml
bridgetown-builder/.rubocop.yml
bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
bridgetown-core/lib/bridgetown-core/tags/render_content.rb
bridgetown-paginate/.rubocop.yml
bridgetown-paginate/lib/bridgetown-paginate/pagination_generator.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_indexer.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_model.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_page.rb
bridgetown-paginate/lib/bridgetown-paginate/paginator.rb
bridgetown-website/plugins/builders/tags.rb
bridgetown-website/src/_docs/erb-and-beyond.md

I thought it would be a good exercise to—y'know—make sure the "ERB and Beyond" documentation page is itself using ERB instead of Liquid. In doing so I discovered I needed to fix the `liquid_render` helper so it uses `capture`. Will require a point release for 0.18.

Convert ERB and Beyond docs to ERB and use capture helper for liquid_render

---

bridgetown-core/features/template_engines.feature
bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
bridgetown-core/lib/bridgetown-core/converters/liquid_templates.rb

…and check before conversions. This fixes #176
Basically we only want one template engine at a time per file. No Liquid + ERB, no ERB + Slim, whatever. Doesn't make sense. So this code guarantees mutual exclusivity. It's a little verbose and not great on the DRY metric, so I'll look into adding additional smarts to the `Converter` parent class so the individual converters can get cleaned up a bit. But for now, this should work.

For template engine converters, set template_engine frontmatter automatically

---

bridgetown-core/lib/site_template/package.json
bridgetown-website/package.json

Adds a new script to our main `package.json` template, as well as the Bridgetown website.
`yarn clean`
Much like the build and serve commands, this is simply a npm script wrapping a BridgetownRB command.
Once executed, Bridgetown will search for files in the following locations:
- `./output`
- `./.bridgetown-metadata`
- `./.bridgetown-cache`
- `./.bridgetown-webpack`
If there are files present, it will remove them. Essentially clearing your cache and all remenants of the last build.
If the directory is empty, Bridgetown will alert you with something like: `Cleaner: Nothing to do for './.bridgetown-webpack'`
The only downside I can think of it people cleaning so much that it ends up removing some of the value that the caching is providing. However, this could also just be an indicator of …

feat: add `yarn clean` script to package.json

---

CHANGELOG.md
README.md
bridgetown-core/lib/bridgetown-core/utils/ruby_exec.rb

Hey there, I really like the idea of this project and your aims for it! I've got a Jekyll blog myself and I think it's really neat that Bridgetown fills a similar role, while at the same time being more in tune with the direction of the modern web (including webpack as a default, etc.). Additionally, the content of `CONTRIBUTING.md` and `PULL_REQUEST_TEMPLATE.md` is very well written, and it's quite ingenious of you to let contributors include mention of themselves in the `README.md`. I guess you could say that I'm just impressed all around 😄 
This is just a very small PR to get my feet wet with Bridgetown. It doesn't add any tests, but as it's just a simple change to the logging level, I don't feel that tests are warranted.
Closes #175.

Change logging level for "Executing inline Ruby…" messages

---

CHANGELOG.md
README.md
bridgetown-core/lib/bridgetown-core/commands/new.rb
bridgetown-core/lib/site_template/package.json.erb
bridgetown-core/test/test_new_command.rb

✅ I've added tests (if it's a bug, feature or enhancement)
✅ The test suite passes locally (run `script/cibuild` to verify this)
When we create a new Bridgetown site, the default `package.json` has a `name` attribute of `bridgetown-new-site`. 
I thought it would be a nicer developer experience if this name could be inferred from the path entered into the `new` command. So this change takes the last path component of the input path and sets that as the name in `package.json`.

Add inferred name attribute to default package.json

---

bridgetown-core/lib/site_template/src/_components/footer.liquid

Interestingly, I've run the test suite locally and this change didn't break any (so the footer might not be 100% tested?)
One of the first changes I've made to the project I'm setting up right now, perhaps interesting for other folks as well?! Properly linking the site email in the generated `<footer>`.
No correlated issue found.

Add `mailto:`-`<a>`-tag to generated footer

---

bridgetown-website/src/_docs/plugins/generators.md

This PR fixes a small typo in the "Generators" documentation page. The code snippet incorrectly used the method `generate` rather than `generator`.

Fix typo in generators page in docs

---

bridgetown-website/src/_docs/plugins.md
bridgetown-website/src/_docs/plugins/generators.md
bridgetown-website/src/_docs/plugins/helpers.md
bridgetown-website/src/_docs/plugins/tags.md

Documentation fixes on the `plugins/tags` and `plugins/helpers` pages where it seems a class was declared with `def`. I've just replaced `def` with `class`.
This PR fixes #197

Fix class declaration keyword in liquid tags and helpers docs

---

.github/workflows/build.yml
bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/test/test_generated_site.rb

Adding this to our test matrix, and if there are Ruby 3-specific issues with the test suite we can fix those and merge into this branch.

Add Ruby 3.0 preview 2 to the build action

---

bridgetown-website/src/_docs/deployment.md

The paths do not seem to be correctly generated, but it otherwise works.
<!--
Thanks for creating a Pull Request! Before you submit, please make sure
you've done the following:
Add information for deploying on GitLab pages
No corresponding issue.

WIP: Add deployment info for GitLab Pages

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/ruby_template_view.rb

Fix for #73 
In addition, I added the `starts_with? ends_with?` aliases as well as string inquiry for the Bridgetown environment, so you can now call `Bridgetown.environment.production?` just like in Rails. :)

Improve our active ActiveSupport support =)

---

bridgetown-core/lib/bridgetown-core/commands/new.rb
bridgetown-core/lib/bridgetown-core/commands/plugins.rb

Inspired by the Rails team changing their repo's default branch to `main`; I thought we should make it so all new Bridgetown sites and plugins have a `main` branch by default.

Change the default branch name of new bridgetown sites and plugins to `main`

---

bridgetown-core/lib/bridgetown-core/configurations/bt-postcss.rb
bridgetown-core/lib/bridgetown-core/configurations/bt-postcss/postcss.config.js
bridgetown-website/src/_docs/bundled-configurations.md

I've added a configuration for PostCSS plugins as discussed in https://github.com/bridgetownrb/bridgetown/issues/207.
I decided to go with this color adjustment plugin: https://github.com/postcss/postcss-color-function, instead of the one @jaredcwhite recommended. That one was logging a deprecation/incompatibility message with PostCSS 8. The one I included is also an official PostCSS plugin so in my mind that's better.
Any and all feedback appreciated :) 
Closes https://github.com/bridgetownrb/bridgetown/issues/207

Add Bridgetown recommended postcss plugins configuration

---

bridgetown-website/src/_docs/bundled-configurations.md

A small grammar fix on the bundled configurations docs page

Fix grammar on bundle configurations docs page

---

bridgetown-website/src/_docs/erb-and-beyond.md

https://github.com/bridgetownrb/bridgetown/pull/177 disallows usage of Liquid and ERB within the same file. As such I don't think the "Turning off Liquid processing" section (https://www.bridgetownrb.com/docs/erb-and-beyond#turning-off-liquid-processing) in the docs is valid any more.
If I've understood correctly; I think we should just be able to remove this section. Please correct me if I'm wrong @jaredcwhite :)

Remove docs about turning off liquid processing in frontmatter

---

bridgetown-core/lib/bridgetown-core/commands/configure.rb

The `configure` command prints out a list of bundle configurations we include but no info about what is what. I reckon it's a good idea to include a link to the docs page for bundled configurations when `configure` is invoked without args. 
The output will now look like:
```
$ bundle exec bridgetown configure
Please specify a valid packaged configuration from the below list:
bt-postcss
minitesting
netlify
tailwindcss
turbo
stimulus
swup
purgecss
For more info, check out the docs at: https://www.bridgetownrb.com/docs/bundled-configurations
```

Add link to docs when configure command is invoked without arguments

---

.github/workflows/build.yml

Since Ruby 3.0 is out already, no need to test against release candidate.

 Update test matrix to Ruby 3.0.0

---

bridgetown-core/lib/bridgetown-core/related_posts.rb
bridgetown-core/test/test_related_posts.rb

It seems that when using LSI to get related post, the first one is always current post (because, well, it _is_ the best match). This PR fixes it by manually removing current post from the result set. What's interesting is that Jekyll has exactly the same code as Bridgetown, but seems unaffected (i.e. I'm not getting current post as related, but on the other hand I use a bit old version of jekyll + classifier-reborn, maybe it's due to that).

Exclude current post from LSI-powered related posts

---

bridgetown-core/features/webpack_path_tag.feature
bridgetown-core/lib/bridgetown-core/utils.rb
bridgetown-core/lib/site_template/webpack.config.js.erb
bridgetown-website/src/_docs/frontend-assets.md
bridgetown-website/src/_docs/static_files.md

Also provide better Webpack config support for multiple entry points.
So know you can do `{% webpack_path some/path/to/file.png %}`. (works with equivalent ERB helper too)
Fixes #246 #241

Allow arbitrary file names for `webpack_path` helper/tag

---

bridgetown-website/start.js

Brand new user of Bridgetown (yay!) and couldn't get the default site loading on `localhost` by following the getting started steps. Turns out I'm on Windows 10 and it doesn't know how to handle `sleep 8;` within my shell. 
I updated the command to allow the `sleep` plus running the next command. Now it works on my Windows10 and my Mac, but I have no other platform to test / verify.
Couldn't find a related issue, but could also be my search-fu not working.

update start.js script to work on win10

---

bridgetown-core/lib/site_template/package.json.erb
bridgetown-core/lib/site_template/webpack.config.js.erb

This is a 🙋 feature or enhancement, addressed in issues #278 and #273 to update the deprecated `node-sass` package.

Migrate to dart sass since node-sass is deprecated

---

bridgetown-website/Gemfile
bridgetown-website/src/_docs/command-line-usage.md

The `configure` command was missing from the "Command Line Usage" page on the website. This PR adds that in.

Add configure command to command line page on website

---

bridgetown-core/lib/bridgetown-core/commands/concerns/git_helpers.rb
bridgetown-core/lib/bridgetown-core/commands/new.rb
bridgetown-core/lib/bridgetown-core/commands/plugins.rb

To set the default branch name in new bridgetown sites and plugins, we're currently using a flaky if/then line of shell script that checks if the branch name is `master` and updates it to `main` if it is.
A PR just got merged into Rails where this is implement in a more robust way that checks the git config for a default branch name first and sets the default branch to main only if it doesn't exist:
https://github.com/rails/rails/pull/40254/files
Copying the code from there I've improved the logic we use to set the default branch.

Consider the default branch from the git config while create a new site or plugin

---

bridgetown-core/lib/bridgetown-core/commands/configure.rb
bridgetown-core/lib/bridgetown-core/configurations/bt-postcss.rb
bridgetown-core/lib/bridgetown-core/configurations/tailwindcss.rb

Currently the `bridgetown configure` command invokes `bridgetown apply` under the hood. I've tweaked it so the configure command now directly calls Thor's `apply` method to execute the bundled configurations.
Going forward this will allow us to expose utility methods and instance variables (like `@site` potentially) just to our bundled configuration scripts and keep them isolated from what we expose to third party automations.

Make configure command independent of Apply command

---

bridgetown-core/lib/bridgetown-core/concerns/site/localizable.rb
bridgetown-core/lib/bridgetown-core/frontmatter_defaults.rb

This is a 🐛 bug fix. 
One of my plugins' tests were logging the following lines:
`frontmatter_defaults.rb:16: warning: instance variable @glob_cache not initialized`
`localizable.rb:8: warning: instance variable @locale not initialized`
This PR fixes those by checking if those instance variables were `defined?` rather than if they exist.

Fix warnings in plugin tests by checking if an ivar was defined

---

bridgetown-core/lib/site_template/webpack.config.js.erb

Add new configuration to overt webpack warning

---

bridgetown-core/lib/bridgetown-core/commands/webpack/enable-postcss.rb
bridgetown-core/lib/site_template/package.json.erb

When enabling postcss using `bridgetown webpack enable-postcss`, it only updates the webpack config and doesn't install the required packages. Adding a step to install the required postcss packages and uninstall the sass packages.
I also pulled in the default postcss config from the site template instead of creating an empty file

Install required packages in webpack enable postcss tool

---

bridgetown-core/lib/bridgetown-core/commands/webpack/setup.rb
bridgetown-core/lib/bridgetown-core/commands/webpack/update.rb
bridgetown-core/lib/bridgetown-core/commands/webpack/webpack.config.js
bridgetown-core/lib/bridgetown-core/commands/webpack/webpack.defaults.js.erb
bridgetown-core/test/test_new_command.rb
bridgetown-core/test/test_webpack_command.rb
bridgetown-website/src/_docs/frontend-assets.md

Adding a `config` directory in the root project directory and moving the default webpack config into it. In future releases a lot more stuff will be moved into this directory.
https://github.com/bridgetownrb/bridgetown/discussions/271

Add config directory and move webpack defaults into it

---

bridgetown-core/lib/bridgetown-core/configurations/bt-postcss.rb
bridgetown-core/lib/bridgetown-core/configurations/tailwindcss.rb

The `tailwindcss` and `bt-postcss` bundled configurations overwrite the `postcss.config.js` and the only place this is documented is on the website.
This PR adds a confirmation that informs the user that the `postcss.config.js` will be overwritten and asks if they would like to proceed.
Any confusion with running these two configurations one after the other should hopefully be prevented with this warning.
One area we should improve in the future is perhaps silence this warning when the config is invoked as part of `bridgetown new` but for now I reckon this should be good enough.
Closes https://github.com/bridgetownrb/bridgetown/issues/315

Add confirmation for overwriting postcss config in tailwindcss and bt-postcss bundled configurations

---

bridgetown-core/lib/bridgetown-core/commands/webpack/webpack.defaults.js.erb

I have some ideas for enhancing the webpack CLI took in the future ... potentially for 0.22. I think users should be able to update the webpack defaults from a specific version of Bridgetown. 
Say we ship a small update to the config in 0.22 and then a big one in 0.23. The user upgrades directly from 0.21 to 0.23; they cannot now access the 0.22 version of the webpack defaults.
The user should be able to optionally pass in a Bridgetown version like: `bridgetown webpack update 0.22` and this will get the appropriate file from GitHub using the release tag and install it locally.
As a first step to this I think it's useful for the user to see which version of Bridgetown their existing webpack defaults shipped with; this PR adds that in.

Add Bridgetown version to webpack defaults

---

bridgetown-core/features/hooks.feature
bridgetown-core/lib/bridgetown-core/concerns/layout_placeable.rb
bridgetown-core/lib/bridgetown-core/layout.rb
bridgetown-core/lib/bridgetown-core/readers/layout_reader.rb
bridgetown-core/lib/bridgetown-core/resource/base.rb
bridgetown-core/test/resources/src/_layouts/default.erb
bridgetown-core/test/resources/src/top-level-page.md
bridgetown-core/test/test_resource.rb

Also a `label` method to `Layout`.
Fixes #323

Add `layout` method to `Resource::Base`

---

bridgetown-core/test/test_new_command.rb
bridgetown-core/test/test_webpack_command.rb

Looking into the test failure, it looks like the suite crashes when trying to create a new site in `test_webpack_command` and `test_new_command` due to a directory conflict.
In some cases, the new site's directory isn't totally cleaned up when running the whole test suite; not the individual case. I have no idea why it doesn't get cleaned up, can't see anything in to code to suggest it. 
Locally, I changed the hardcoded name of `new-site` and replaced it with `SecureRandom.alphanumeric` and it seemed to pass consistently. I think this is the right way to go as it would stand us in good stead if we were to parallelize the test suite in the future.
If anyone has any ideas as to why the directory isn't cleaned up sometimes, please let me know!
Opening this PR to see if CI passes …

Attempting to stabilize test suite

---

bridgetown-core/lib/bridgetown-core/commands/webpack/webpack.config.js
bridgetown-core/lib/site_template/package.json.erb

I've been knee deep in Webpacker 6 today and I discovered the amazing [`webpack-merge`](https://github.com/survivejs/webpack-merge) package to merge config objects.
I thought it'd be a good idea to include it in new sites by default and add some docs about how to use it.

Add webpack merge docs  to webpack config

---

bridgetown-website/src/_docs/deployment.md

I noticed that there's no description in the docs for how to build and deploy a Bridgetown site on GitHub Pages. I'm using the [bridgetown-gh-pages-action](https://github.com/andrewmcodes/bridgetown-gh-pages-action) GitHub Action to do so and after a little help from the author it's a very easy solution, so I thought I'd help out others who might not be aware of it by including it in the docs.
Updates the deployment docs for GitHub Pages.

Add a deployment description for GH Pages to the docs

---

bridgetown-website/src/_docs/installation/macos.md

Apple switched the default shell to zsh from bash in macOS 10.15 (Catalina), and
so instructions to update `~/.bash_profile` are incorrect. This change updates
the documentation to instead use `~/.zprofile`.

Update macOS documentation to refer to zsh instead of bash

---

bridgetown-core/lib/site_template/package.json.erb

The package.json was missing a comma after the `"webpack-manifest-plugin": "^3.1.1"` line, which broke the installation.

Add mission comma in package.json which broken install

---

bridgetown-website/src/_docs/collections.md

Fix broken link to page about "static files"

---

bridgetown-core/lib/site_template/frontend/javascript/index.js.erb
bridgetown-core/lib/site_template/package.json.erb

Removes empty lines in package.json when creating a new site. 
The following will close issue #368 when PR is merged.

Fix strip out newlines in generated package.json

---

bridgetown-website/src/_docs/template-engines.md

In Bridgetown documentation, the spelling of the word hindrance is hinderance which is incorrect.
The wrong word hinderance has been replaced by the correct word hindrance in this PR.

Correct spelling of the word hindrance ✏️ 

---

bridgetown-core/features/webpack_path_tag.feature
bridgetown-core/lib/bridgetown-core/concerns/site/content.rb
bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
bridgetown-core/lib/bridgetown-core/errors.rb
bridgetown-core/lib/bridgetown-core/utils.rb

The PR addresses a performance issue with the code which parses the Webpack manifest JSON file. Previously the loading and parsing of the file was happening every single time the Webpack helper was used…meaning if you had to generate 10,000 pages, the loading/parsing of the manifest occurred 10,000 times. Now it happens once. 😁
Bonus: you now have access to `site.frontend_manifest` in Ruby anytime you need direct access to the contents of the manifest.
Fixes #325

Performance refactor of the Webpack helper

---

bridgetown-core/lib/site_template/package.json.erb

There's a bug in `postcss-focus-within` v3 which has been fixed in v4; but `postcss-present-env` still relies on v3. There's a PR open to update it for over a year: https://github.com/csstools/postcss-preset-env/pull/172
To provide a better developer experience, I reckon it's best to fix this within Bridgetown by explicitly resolving this package to v4. I've set the resolution in our default `package.json`. I don't think there's much point in adding this resolution just when the `--use-postcss` flag is added as it doesn't really do any harm and I don't want to litter the file with multiple `if`s.
Also, this approach means we don't have to set the resolution in our `bridgetown webpack enable-postcss` command which makes life easier as the `yarn set resolution` command only exists in Yarn …

Resolve postcss-focus-within to v4

---

bridgetown-core/lib/bridgetown-core/generators/prototype_generator.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_model.rb

Allow symbols for use in pagination/prototype front matter

---

bridgetown-core/lib/bridgetown-core/collection.rb
bridgetown-core/lib/bridgetown-core/resource/relations.rb

Previously, if you had an array of resource relations using `belong_to`, the result set would not be ordered in the same way as your front matter. Now you get exactly the results you specify. For example:
```yaml
pages: ["posts", "404", "about", "404", "posts"]
```
calling `resource.relations.pages` will literally retrieve an array of resources in that order (posts, 404, about, 404, posts).
Resolves #360

Return ordered results for belongs_to array

---

bridgetown-website/Gemfile

No need pin ruby2js here.

---

bridgetown-core/lib/bridgetown-core/commands/console.rb

Inspired by Rails' `ConsoleMethods` technique, this PR adds a `Bridgetown::ConsoleMethods` module which mixes into IRB's main context. In addition to `site`, you can now access the `collections` shorthand, and you can also run `reload!` which will reload all plugins and reset/reread the site.
Also cool is you can extend `ConsoleMethods` to add your own commands to the console!
```ruby
module ConsoleMethods
def ruby_rocks
"MINASWAN!"
end
end
Bridgetown::ConsoleMethods.include ConsoleMethods
```
```
bin/bridgetown c
irb> ruby_rocks
=> "MINASWAN!"
```

Add new console commands via `ConsoleMethods` mixin

---

bridgetown-core/.rubocop.yml
bridgetown-core/bridgetown-core.gemspec
bridgetown-core/lib/bridgetown-core/converters/serbea_templates.rb
bridgetown-core/test/resources/src/_pages/i-am-ruby.rb
bridgetown-core/test/source/src/_components/nested.erb
bridgetown-core/test/source/src/_components/nested_serb.rb
bridgetown-core/test/source/src/_components/nested_serb.serb
bridgetown-core/test/source/src/_layouts/serblayout.serb
bridgetown-core/test/source/src/_partials/testing/_partials.serb
bridgetown-core/test/source/src/page_using_serb.serb
bridgetown-core/test/test_filters.rb
bridgetown-core/test/test_layout_reader.rb
bridgetown-core/test/test_resource.rb
bridgetown-core/test/test_serbea.rb
bridgetown-core/test/test_site.rb
bridgetown-website/frontend/styles/syntax.scss
bridgetown-website/src/_docs/erb-and-beyond.md
bridgetown-website/src/_docs/template-engines.md
bridgetown-website/src/_pages/plugins.serb

Resolves #277 
See https://github.com/bridgetownrb/bridgetown/pull/440/files#diff-eaec747a8ae0268efeebcc6533c86d56507233c1a578d1e0c323c30d01ddd360 for an example of converting a Liquid template into a Serbea template. Pretty similar! (That's the whole point! 😄)

Integrate Serbea 1.0 into Bridgetown

---

bridgetown-core/.rubocop.yml
bridgetown-core/bridgetown-core.gemspec
bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
bridgetown-core/lib/bridgetown-core/utils/loaders_manager.rb

This fixes a nasty bug where classes were being duplicated in dev with Zeitwerk reloads and `ActiveSupport::DescendantsTracker`. So for example you'd have a `Post` subclass of `Bridgetown::Model::Base`, and you'd reload, and now you'd have two `Post`s, reload again, and you'd have three `Post`s, etc. Argh. Now descendant classes are specifically removed from the descendants tree upon unload.

Fix class duplication bug with reloads

---

bridgetown-core/lib/bridgetown-core/commands/console.rb
bridgetown-core/lib/bridgetown-core/concerns/site/extensible.rb
bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
bridgetown-core/lib/bridgetown-core/concerns/site/ssr.rb
bridgetown-core/lib/bridgetown-core/configurations/minitesting.rb
bridgetown-core/lib/bridgetown-core/generators/prototype_generator.rb
bridgetown-core/lib/bridgetown-core/hooks.rb
bridgetown-core/lib/bridgetown-core/rack/roda.rb
bridgetown-core/lib/bridgetown-core/watcher.rb
bridgetown-paginate/lib/bridgetown-paginate/hooks.rb
bridgetown-website/src/_docs/plugins/hooks.md

Just a bit of a Hooks refactor, plus getting rid of the React-like "store a second hook via a proc returned from the original hook" weirdness in the SSR plugin (*shudder*…what was I thinking?!) in favor of using regular site hooks. (Speaking of which, `site` now has a pretty nice `on` method…)
Plus Hooks now has YARD documentation.
…OK, ended up refactoring Watcher as well. 😅

A bit of a hooks refactor & cleaning up SSR reload hook

---

bridgetown-core/lib/bridgetown-core/drops/drop.rb
bridgetown-core/lib/bridgetown-core/drops/resource_drop.rb
bridgetown-core/lib/bridgetown-core/resource/base.rb

Normalize previous/next resource API between Ruby and Liquid

---

bridgetown-core/lib/bridgetown-core/model/base.rb
bridgetown-core/lib/bridgetown-core/model/repo_origin.rb
bridgetown-core/test/test_model.rb

Resolves #451 
One gotcha that dawned on me as I was working on this is any file with Ruby front matter (aka not YAML) would potentially get overwritten with YAML front matter. Might need to add a check for that and raise an error so there's never accidental data loss.

Allow saving of models with repo origin

---

bridgetown-core/lib/bridgetown-core/configurations/vercel.rb
bridgetown-core/lib/bridgetown-core/configurations/vercel/vercel.json
bridgetown-core/lib/bridgetown-core/configurations/vercel/vercel_url.rb
bridgetown-website/src/_docs/bundled-configurations.md

Adds a bundled configuration for Vercel with correct security headers and content type for feeds.xml (if using the RSS plugin).
It also correctly assigns the Bridgetown URL to the VERCEL_URL in non-production environments. This means that if a VERCEL_URL is in the environment, whether production or running via Vercel's CLI locally, the absolute url's will adjust accordingly.
See example of it in use in the [deploys on this PR](https://github.com/andrewmcodes/bridgetown-vercel-demo/pull/1)
I spoke about this with Jared. I think pre-1.0 we should make the deployment path to whatever service of your choosing as simple as possible without any need to dig into why something is behaving odd.

feat: add bundled configuration for Vercel

---

bridgetown-core/lib/bridgetown-core/configurations/stimulus.rb

I haven't written a test for this change because AFAIK bundled configurations are not included in tests. But let me know if you'd like me to add a test. I did run the tests, though, and none are failing. I also manually tested my changes (more on that below).
I've made minor changes to the code that the Stimulus bundled configuration adds to `index.js`, so that Stimulus controllers are detected and named according to the Stimulus docs: https://stimulus.hotwired.dev/handbook/installing#controller-filenames-map-to-identifiers. Specifically, my changes ensure the following:
- If a Stimulus controller has a name longer than one word, and if the words are separated by underscores in the filename, then in the HTML identifier the words are separated by hyphens and not …

Map Stimulus controller filenames to identifiers as in the Stimulus docs

---

bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb
bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
bridgetown-core/lib/bridgetown-core/converters/serbea_templates.rb
bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
bridgetown-core/lib/bridgetown-core/site.rb
bridgetown-website/src/_docs/plugins.md
bridgetown-website/src/_docs/plugins/cache-api.md

Partials rendering speedup by nearly 8x (!)

---

bridgetown-website/src/_docs/bundled-configurations.md
bridgetown-website/src/_docs/command-line-usage.md

Just a few housekeeping changes for the docs:
- Add the `--configure=` option for `bridgetown new` to [Command Line Usage](https://edge.bridgetownrb.com/docs/command-line-usage). (It is already documented in [Bundled Configurations](https://edge.bridgetownrb.com/docs/bundled-configurations).)
- Replace `swup` with `turbo` in the example in [Bundled Configurations](https://edge.bridgetownrb.com/docs/bundled-configurations).
- ~~Fix the broken links to the postcss-preset-env site under recommended PostCSS plugins in [Bundled Configurations](https://edge.bridgetownrb.com/docs/bundled-configurations).~~
- ~~[preset-env.cssdb.org](https://preset-env.cssdb.org) no longer exists. [cssdb.org](https://cssdb.org) exists, but it seems the postcss-preset-env content …

Site fixes

---

bridgetown-website/src/_docs/installation/windows.md

Minor documentation addition regarding an issue with the Windows Subsystem for Linux (V2) and live-reload. Namely that when a live-reload server has been initialized outside of the Linux file system, live-reload will stop working and assets won't properly called on fresh builds. 
Linked the open issue on the Microsoft repo for context, provided some advice and an extension that may facilitate workflow when interacting with the WSL.
Ran into this issue myself when attempting to build a Bridgetown website on an install of Windows with WSL 2 installed. 
I tried to match tone; I wasn't aware of a style guide for the docs so I tried my best. Let me know revisions are needed!

Documentation: Added a heads up regarding the WSL and Live-reload

---

bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
bridgetown-core/lib/bridgetown-core/configurations/gh-pages.rb
bridgetown-core/lib/bridgetown-core/configurations/gh-pages/gh-pages.yml
bridgetown-core/lib/site_template/bridgetown.config.yml

Improve the DX when using GH pages.
I've added a bundled configuration that sets up a GH action to deploy the site to GH pages. The configuration also prints out some helpful info to the user about using the `base_path` config option as this is likely necessary with Pages.
Resolves #420

Add bundled configuration for GH pages

---

bridgetown-website/src/_docs/deployment.md

Amending the docs on the deployment page to refer to the new GH pages bundled configuration

Update deployment docs for GH pages

---

README.md
bridgetown-core/lib/bridgetown-core/utils/require_gems.rb
bridgetown-website/src/_posts/2020/2020-04-17-time-to-visit-bridgetown.md
bridgetown-website/src/_posts/2020/2020-04-18-whats-the-deal-with-themes.md
bridgetown-website/src/_posts/2020/2020-05-18-whats-new-in-0.14-hazelwood.md
bridgetown-website/src/_posts/2020/2020-06-18-major-workflow-advances-in-0.15-overlook.md
bridgetown-website/src/_posts/2020/2020-07-28-whats-new-in-0.16-crystal-springs.md
bridgetown-website/src/_posts/2020/2020-08-11-bulmatown-theme-and-snipcart.md
bridgetown-website/src/_posts/2020/2020-08-25-midsummer-2020-plugin-roundup.md

This is a 🔦 documentation change. There are some  community link broken, as actual community url is *https://www.bridgetownrb.com/community*
Fixed broken community url in some doc and posts.

Fixed “Community” url typo

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/plugin.rb
bridgetown-core/lib/bridgetown-core/plugin_manager.rb
bridgetown-core/lib/bridgetown-core/utils/aux.rb

Addresses bug report: https://github.com/bridgetownrb/bridgetown-activerecord/issues/1

Fix bug where sidecar aux process wasn't requiring bundler groups

---

bridgetown-core/lib/bridgetown-core/rack/roda.rb
bridgetown-core/lib/bridgetown-core/resource/destination.rb
bridgetown-core/test/source/src/contacts/rails-style.html.erb
bridgetown-core/test/test_erb.rb
bridgetown-core/test/test_filters.rb
bridgetown-core/test/test_site.rb

Issue warning when a Rails-style extension is used (like `.html.erb`)

---

.rubocop.yml
bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb
bridgetown-core/lib/bridgetown-core/concerns/localizable.rb
bridgetown-core/lib/bridgetown-core/concerns/site/configurable.rb
bridgetown-core/lib/bridgetown-core/drops/generated_page_drop.rb
bridgetown-core/lib/bridgetown-core/drops/resource_drop.rb
bridgetown-core/lib/bridgetown-core/filters/url_filters.rb
bridgetown-core/lib/bridgetown-core/generated_page.rb
bridgetown-core/lib/bridgetown-core/plugin.rb
bridgetown-core/lib/bridgetown-core/resource/base.rb
bridgetown-core/lib/bridgetown-core/resource/relations.rb
bridgetown-core/lib/bridgetown-core/utils.rb
bridgetown-core/test/resources/src/_layouts/localization.serb
bridgetown-core/test/resources/src/_noodles/ramen.liquid
bridgetown-core/test/resources/src/_pages/multi-page.md
bridgetown-core/test/resources/src/_pages/second-level-page.en.md
bridgetown-core/test/resources/src/_pages/second-level-page.fr.md
bridgetown-core/test/test_filters.rb
bridgetown-core/test/test_locales.rb
bridgetown-paginate/lib/bridgetown-paginate/pagination_model.rb

In this PR, resources and generated pages now offer an `all_locales` method. Calling this will return all of the resources (or generated pages) with the same slug…i.e. all the locales of that resource/page. For example:
`/some-page`
`/es/some-page`
`/zh-CN/some-page`
etc.
This also adds automatic support for multi-locale paginated pages (aka the English "Posts" page will show only English links, Spanish "Publicación" page will show only Spanish links, etc.).
Addresses #49

Allow finding and linking to alternate locale pages

---

bridgetown-website/src/_docs/philosophy.md

Fixes a typo in the ["Core Principles" section](https://www.bridgetownrb.com/docs/philosophy#core-principles) on the "Our Philosophy" page of the Bridgetown website.
As this is a trivial typo fix and the typo didn't distort the meaning, I do not regard it as a "notable change" and am thus not adding an entry for it to the top of `CHANGELOG.md` nor adding myself to the contributors at the bottom of `README.md`.
I did not file an issue for this.

fix typo: "focsued" → "focused"

---

bridgetown-core/lib/site_template/README.md

Discovered a typo in the `README.md` for the site template when updating my own based on said template.
`s/tranditional/traditional`
(aside: the file ending seems to be different in my contribution, so it's picking that up, too. Not sure why ¯\_(ツ)_/¯)

Fixes a typo in the site template repo README

---

bridgetown-core/lib/bridgetown-core/commands/plugins.rb

CI is failing due to a Rubocop error. The suggested fix won't work in this case so shutting it up ....

Silence rubocop

---

bridgetown-core/lib/bridgetown-core/commands/new.rb
bridgetown-core/lib/site_template/frontend/javascript/index.js.erb
bridgetown-core/lib/site_template/frontend/styles/syntax-highlighting.css
bridgetown-core/test/test_new_command.rb

This change adds a default theme for syntax highlighting so users
can see the full power of syntax highlighting when they create a
new bridgetown app.
The theme is stored in a new `syntax-higlighting.css` files.
- Closes #512
- This is a draft PR to promote discussion on this potential enhancement. I know there are further discussions happening in the issue, but perhaps this could be a good first step, or perhaps it will just help aid the ongoing conversation.
- This PR is unfinished, but I wanted to get something up and get feedback first. The things I know are missing are:
- Upgrade path
- Changelog
- Documentation eg. perhaps extract Syntax Highlighting out of [liquid tags docs](https://www.bridgetownrb.com/docs/liquid/tags#stylesheets-for-syntax-high …

Apply default theme for syntax highlighting

---

bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/lib/bridgetown-core/converters/markdown/kramdown_parser.rb
bridgetown-core/lib/bridgetown-core/kramdown/parser/gfm.rb
bridgetown-core/test/test_kramdown.rb
bridgetown-website/src/_docs/configuration/markdown.md
bridgetown-website/src/_docs/configuration/options.md

Many Markdown editors allow you to highlight text with `::double colons::` or with `==double equals==`. I've grown accustomed to this myself in various writing contexts. Because of that, it's frustrating to have to switch gears in Bridgetown `.md` files and add `<mark>` tags everywhere instead.
This PR patches Kramdown's GFM parser (our default) to add support for both those delimiters. So for example:
```md
This is ==now highlighted==! ::Yay!::
```
becomes
```html
This is <mark>now highlighted</mark>! <mark>Yay!</mark>
```
The `kramdown: mark_highlighting` YAML config option can be set to `false` to disable this new feature if for some reason it's a breaking change for existing websites.

Add Markdown support to convert `==` / `::` to `<mark>`

---

bridgetown-core/lib/bridgetown-core/configurations/tailwindcss.rb

Resolves #547
To set it up in an existing project, just make sure you've added `frontend/styles/jit-refresh.css` to your `.gitignore` file (you might have to delete it and commit first). Then update your `Rakefile` so it has the line
```ruby
sh "touch frontend/styles/jit-refresh.css"
```
right at the top of both the `:build` task and the `:dev` task. For example:
```ruby
namespace :frontend do
desc "Build the frontend with esbuild for deployment"
task :build do
sh "touch frontend/styles/jit-refresh.css"
sh "yarn run esbuild"
end
desc "Watch the frontend with esbuild during development"
task :dev do
sh "touch frontend/styles/jit-refresh.css"
sh "yarn run esbuild-dev"
rescue Interrupt
end
end
```

Update Tailwind config so `jit-refresh.css` is git ignored

---

.rubocop.yml
bridgetown-core/.rubocop.yml
bridgetown-core/lib/bridgetown-core/rack/roda.rb
bridgetown-core/lib/site_template/server/roda_app.rb
bridgetown-core/test/ssr/server/roda_app.rb
bridgetown-core/test/ssr/server/routes/cookies.rb
bridgetown-core/test/ssr/server/routes/ooh_json.rb
bridgetown-core/test/test_ssr.rb
bridgetown-routes/lib/bridgetown-routes.rb
bridgetown-website/server/roda_app.rb
bridgetown-website/src/_docs/routes.md

Instead of the main Roda app having to call `Bridgetown::Rack::Routes.start! self`, it can just use `r.bridgetown`.
Also made sure cookies support indifferent access (symbols as well as strings). Added more route tests to the suite.

Simplify the Roda boot process, add more route tests

---

bridgetown-core/lib/site_template/bridgetown.config.yml

This commit adds a link to the configuration options docs directly into the default `bridgetown.config.yml`. This will make navigating to the docs quicker and will also increase discoverability of those options for folks getting started with Bridgetown.
I often need to reference the configuration options docs when updating my site config. Typically, I have to navigate to the Bridgetown site, and then search/find the link for the configuration options, which takes several clicks and can break my concentration. This change will also ensure that the options are easily discoverable in case someone has trouble finding them on the website.
Not a necessity, but it would be nice to have and provide a smoother DX after running `bridgetown new`.

Update site template configuration file with link to config options docs

---

bridgetown-core/lib/bridgetown-core/configurations/tailwindcss.rb

This commit updates the Tailwind CSS content glob to also include ruby files when searching for classes in the src folder.
Components, plugins, helpers, data files, etc. that are written in Ruby may contain Tailwind CSS classes that won't get generated by the JIT because they aren't in the content scope. 
I have been using Tailwind for years but it took me close to 45 minutes before I realized the reason my classes were not generating the right CSS because they were in a Ruby component, not the accompanying erb file. Hopefully this will save people heartache and frustration if they run into the same issue and not make it be something you always need to add when generating a new site with Tailwind.
The one downside to this addition could be a …

feat: add rb files to the Tailwind content glob

---

bridgetown-core/lib/bridgetown-core/errors.rb
bridgetown-core/lib/bridgetown-core/rack/logger.rb
bridgetown-core/lib/bridgetown-core/rack/roda.rb
bridgetown-core/lib/site_template/src/404.html
bridgetown-core/lib/site_template/src/500.html
bridgetown-core/test/ssr/server/roda_app.rb
bridgetown-routes/lib/bridgetown-routes/code_blocks.rb

No more "500 Internal Server Error" pages in development with zero context. Now we get a nice Rails-y Roda exception page with context info, plus much better exception logging. Also adds a 500.html file which would be used in production.

Improve Roda error handling and update static error pages

---

bridgetown-builder/lib/bridgetown-builder.rb
bridgetown-builder/lib/bridgetown-builder/builder.rb
bridgetown-builder/lib/bridgetown-builder/plugin.rb
bridgetown-core/lib/bridgetown-core/commands/plugins.rb
bridgetown-core/lib/bridgetown-core/commands/registrations.rb

Fixes #539 (again!)
Also improves display of `bridgetown plugins list` command and adds a `--verbose` flag for printing source paths.

Ensure gem-based Builders are part of priority sorting

---

bridgetown-core/lib/bridgetown-core/commands/esbuild/migrate-from-webpack.rb

Since SASS is now again supported in 1.1.0 beta2, I wanted to finally update my blog from webpack to esbuild by running `bridgetown esbuild migrate-from-webpack`. However, in the process, I encountered two problems:
* There is a code that check if SASS is used and blocks from migrating if it is - this is now not necessary
* `postcss-load-config` released a new version few days ago with breaking API, which causes generated config to not work. Version pinning to last working versions is needed.

Fix migrate-from-webpack process

---

bridgetown-core/lib/site_template/Gemfile.erb

This commit adds `nokogiri` to the default Gemfile, **commented out**, similar to the way Rails adds commented gems like:
```ruby
```
This should make it more apparent, and harder to miss, that `nokogiri` must be added to the bundle to use the Inspectors API. It uses the `Inspectors API` verbiage to make it easy to search for directly in their editor and make it easier to search for on GitHub as people push public sites with this line it.
The other night, @DRBragg & I were building a site and wanted to test the new Inspectors API. To our dismay, it didn't appear to work and we chalked it up to a bug and were about to give up when my eye finally landed on this line in the docs:
```md
Bridgetown doesn’t directly install the Nokogiri gem, so be sure to run …
```

Update Gemfile template with `nokogiri` commented out

---

bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
bridgetown-core/lib/bridgetown-core/converters/serbea_templates.rb
bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
bridgetown-core/test/source/src/_layouts/serblayout.serb
bridgetown-website/plugins/builders/inspectors.rb
bridgetown-website/src/_docs/template-engines/erb-and-beyond.md

Fixes #575, helps along #581
**NOTE:** This change should be replicated in the Slim and Haml plugins.

Support kwargs-only method calls for `partial`

---

bridgetown-core/lib/bridgetown-core/concerns/site/localizable.rb

Updates I18n.load_path to include subdirectories of src/_locales.
Relates to the first part of #598

Include subdirectories of src/_locales in I18n loader

---

CHANGELOG.md
README.md
bridgetown-core/lib/bridgetown-core/configurations/gh-pages/gh-pages.yml

The current GitHub Pages configuration builds the site using the default `development` environment.
This PR updates the relevant configuration to use the `production` environment instead as I think that's always going to be the intention for this workflow, and it matches other configurations such as [Netlify](https://github.com/bridgetownrb/bridgetown/blob/main/bridgetown-core/lib/bridgetown-core/configurations/netlify/netlify.toml#L7).

Specify production BRIDGETOWN_ENV for Github Pages builds

---

bridgetown-core/lib/bridgetown-core/commands/esbuild/esbuild.config.js

In editors like VSCode which can providing typing and documentation hovers through TypeScript-interpreted JSDoc, this will make it easier to edit the esbuild config and get links to esbuild documentation.

Provide esbuild config typing via JSDoc

---

bridgetown-core/lib/bridgetown-core/helpers.rb
bridgetown-core/test/test_ruby_helpers.rb
bridgetown-website/src/_docs/template-engines/erb-and-beyond.md

Adds the ability to pass a hash to `link_to` (or call `attributes_from_options` to use on any HTML tag) and have the key-value pairs be listed as HTML attributes.
Example:
```ruby
<%= link_to "Label", "/foo/bar", class: "classes", data: { controller: "testable", action: "testable#test" } %>
```
would return:
```html
<a href="/foo/bar" class="classes" data-controller="testable" data-action="testable#test">Label</a>
```
You also have the ability to pass a hash as a keys value and have the values keys merged with the parent key. So:
```ruby
<%= link_to "Label", "/foo/bar", class: "classes", data: { controller: "testable", action: "testable#test", testable: { target: "test_value", index_value: "1" } } %>
```
would return:
```html
<a href="/foo/bar" …
```

feat: Add hash attributes functionality to view tag helpers

---

bridgetown-core/lib/bridgetown-core/helpers.rb
bridgetown-website/src/_docs/template-engines/erb-and-beyond.md

I made a goof in #589. A few of the ERB expressions in the docs for `attributes_from_options` were being evaluated within the template. Adjusting the syntax from  `<%=`  to `<%%=`, so it’s escaped, should fix the issue.
re: Twitter convo w/ @jaredcwhite

Use correct ERB syntax in docs

---

bridgetown-core/lib/bridgetown-core/helpers.rb

Silence a warning under ruby 2.7.
```
site/.direnv/ruby/gems/bridgetown-core-1.1.0/lib/bridgetown-core/helpers.rb:115: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
site/.direnv/ruby/gems/i18n-1.12.0/lib/i18n.rb:210: warning: The called method `t' is defined here
```
Here is a similar fix in Rails, a while ago:
https://github.com/rails/rails/commit/adef6323e682e026ea6bdbf3a6eb187491f0fbd6#diff-9c5e802c729a438537b41a02f0b08eb594855d8bebcd0ff2e3452fc6a999375d
For reference, here is the issue in i18n gem (but I think this must be solved in this repo):
https://github.com/ruby-i18n/i18n/issues/516
***
I've only tested this quickly on my machine, but I think it should work.

Silence keyword arguments warning in ruby 2.7

---

bridgetown-core/lib/bridgetown-core/commands/esbuild/esbuild.defaults.js.erb
bridgetown-core/lib/bridgetown-core/commands/esbuild/migrate-from-webpack.rb
bridgetown-core/lib/bridgetown-core/configurations/lit/esbuild-plugins.js
bridgetown-core/lib/site_template/package.json.erb

This is a 🐛 bug fix (?)
As reported in #591, `postcss-load-config` introduced a breaking change in their latest major version update: `4.x`. Instead of loading the configuration in a synchronous way, it's needed to load the configuration in an asynchronous way.
The PR;
- Allows loading the PostCSS configuration under `postcss-load-config > 4.x` again.
- Updates the `postcss-load-config` references from `3.1.4` to `4.0.1`.
- Updates the template for the `lit/esbuild-plugins` to also use the asynchronous API.
- Updates the naming of the "import" function of the PostCSS plugin to align it with the other "import" functions in the `esbuild.defaults.js`.
I'm a bit rusty on my JavaScript, so I'm looking for feedback on the proposed `async/await` changes. I'm also not sure how I could add a test …

Update `postcss-load-config` to `4.x` and address synchronisation issues (*breaking change*)

---

bridgetown-core/lib/bridgetown-core/commands/esbuild/esbuild.defaults.js.erb

Fixes problems when referencing node_modules that are defining "index.css" themself, such as fontsource-packages. In such cases the manifest would reference the wrong file and the "frontend/index.scss" would be missing from the manifest and produce 404 errors.
This is a 🐛 bug fix. 
Fixes #616

fix: esbuild entrypoint selection for index.css

---

bridgetown-builder/bridgetown-builder.gemspec
bridgetown-paginate/bridgetown-paginate.gemspec
bridgetown-routes/bridgetown-routes.gemspec
bridgetown/bridgetown.gemspec

In trying to get to the repository for `bridgetown`, I noticed that the main gem didn't have metadata set up for RubyGems.org. This change adds the same metadata from `bridgetown-core` to all four other gems in the repository to make it easier to get to the source code and other areas.
[`bridgetown` 1.1.0 on RubyGems.org](https://rubygems.org/gems/bridgetown/versions/1.1.0)

Add gemspec metadata for all gems

---

bridgetown-core/lib/bridgetown-core/concerns/site/localizable.rb
bridgetown-core/test/test_locales.rb

Updates i18n fallback chain to include base languages for regional variants (e.g. fr-CA falls back to fr before en).
Or, more specifically, adds the default locale (and English) to the existing fallbacks defined by the I18n backend.
Second part of #598.

Use regional fallbacks from i18n

---

bridgetown-core/test/test_ssr.rb

- Adding `require "rack"` because Rack no longer seems to be loaded. (Wasn't sure why this was now needed though 🤔.)
- Remove call to `.first` on the return value from `Rack::Builder.parse_file` - in Rack's latest version, [just the app is returned](https://github.com/rack/rack/pull/1663) rather than an array.

Update SSR tests to work with Rack 3

---

bridgetown-website/src/_docs/deployment.md

This PR adds documentation for Dockerfile-based deployments, which should cover a huge number of additional deployment options (Fly.io, Render/Heroku without buildpacks, Railway, etc).
This uses a multi-stage build that I've confirmed to work with my (relatively simple) personal site on Fly.io(https://stephen-dolan.fly.dev). There are a few advantages to multi-stage builds:
- Your final production image is **super small**, and doesn't have to contain ruby or nodejs runtimes.
- You can compile JS and Ruby output separately to keep those respective images really clean. No mucking around with installing nodejs package signatures and specifying hard-coded versions in the `ruby:alpine` image.
I'd welcome any tips regarding how to more effectively/minimally …

Add Dockerfile to deployment options

---

bridgetown-core/lib/bridgetown-core/converters/liquid_templates.rb
bridgetown-core/lib/bridgetown-core/reader.rb
bridgetown-core/lib/bridgetown-core/resource/base.rb
bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
bridgetown-core/lib/site_template/TEMPLATES/erb/_layouts/default.erb
bridgetown-core/lib/site_template/TEMPLATES/erb/_layouts/page.erb
bridgetown-core/lib/site_template/TEMPLATES/erb/_layouts/post.erb
bridgetown-core/lib/site_template/TEMPLATES/liquid/_layouts/default.liquid
bridgetown-core/lib/site_template/TEMPLATES/liquid/_layouts/page.liquid
bridgetown-core/lib/site_template/TEMPLATES/liquid/_layouts/post.liquid
bridgetown-core/lib/site_template/TEMPLATES/serbea/_layouts/default.serb
bridgetown-core/lib/site_template/TEMPLATES/serbea/_layouts/page.serb
bridgetown-core/lib/site_template/TEMPLATES/serbea/_layouts/post.serb
bridgetown-core/test/resources/src/_pages/multi-page.multi.md
bridgetown-core/test/source/src/_layouts/erblayout.erb
bridgetown-core/test/source/src/_layouts/serblayout.serb
bridgetown-website/src/_docs/datafiles.md
bridgetown-website/src/_docs/front-matter.md
bridgetown-website/src/_docs/liquid/filters.md
bridgetown-website/src/_docs/resources.md
bridgetown-website/src/_layouts/default.serb
bridgetown-website/src/_layouts/page.serb
bridgetown-website/src/_layouts/post.serb
bridgetown-website/src/_pages/authors/[author].serb
bridgetown-website/src/_pages/blog.serb
bridgetown-website/src/_pages/blog/[category].serb

Resolves #527 (including @johlym's feature request!)

feat: allow template to use `data` directly instead of `resource.data`

---

bridgetown-paginate/lib/bridgetown-paginate/pagination_indexer.rb
bridgetown-website/src/_docs/front-matter.md

I think this is just a tiny typo. It's called [delimiter](https://www.oxfordlearnersdictionaries.com/definition/english/delimit), right?
Because it's the character that limits strings. Or do I misunderstand something here?
I'm not a native speaker so I might be wrong here.

typo: delimeters => delimiters

---

bridgetown-core/lib/bridgetown-core/configurations/bt-postcss.rb

This is a 🔦 documentation change. (not really, but this is the closest option)
Fixes a typo in a command line prompt that is shown while configuring tailwind.

Fix typo in confirmation prompt

---

bridgetown-core/lib/bridgetown-core/helpers.rb
bridgetown-core/test/test_ruby_helpers.rb

This just adds the possibility to use block syntax as it is possible in `link_to` helpers of other frameworks / builders
PS: It would be nice if you would add the `hacktoberfest-accepted` label to this issue if you find it worthy merging.

extend `link_to` helper to accept blocks

---

bridgetown-core/lib/site_template/config/initializers.rb

This is a 🔦 documentation(ish) change.
Replace documentation link in the initializers site template file that points to the wrong URL.
The site template initializer file points to `/documentation/` instead of `/docs/` resulting in a page not found error when clicking the link. 
As some added context, I couldn't actually find the initializers documentation for a moment, maybe it would be helpful to link to it in some predominate places/on the sidemenu?

fix: update broken initializers documentation link

---

bridgetown-website/src/_docs/template-engines.md

I was recently reading through the documentation of the site when I noticed this typo. Just quickly popped into GitHub to open a correction via the web interface. Let me know if additional steps need to be taken to get this compliant with your PR process.

Correct Typo in `_docs/template-engines.md`

---

bridgetown-core/.rubocop.yml
bridgetown-core/test/test_filters.rb

This PR addresses 2 Rubocop violations that existed in `bridgetown-core/test/test_filters.rb`
* Moving Struct definitions outside a block resolves the `Lint/ConstantDefinitionInBlock` violation.
* At the same time `Style/StructInheritance` could be resolved by using `Foo = Struct.new {}` instead of `class Foo < Struct.new; end`

fix Lint/ConstantDefinitionInBlock and Style/StructInheritance

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
README.md
bridgetown-core/lib/bridgetown-core/utils.rb
bridgetown-core/script/backport-pr
bridgetown-website/src/_docs/content/front-matter-defaults.md
bridgetown-website/src/_docs/deployment.md

In the documentation, there's a lot of references to old named branches `master`. This PR correct them by renaming them `main`. Noteworthy : I didnt' change any coding files (or if so, it was only things commented) in order not to break anything, but with review help I can also manage it if wanted.
Fix #642

Change from master to main

---

CHANGELOG.md
README.md
bridgetown-core/lib/bridgetown-core/collection.rb
bridgetown-core/test/resources/src/_pages/multi-page-with-specified-locales.multi.md
bridgetown-core/test/test_locales.rb
bridgetown-website/src/_docs/internationalization.md

This is a 🙋 feature or enhancement with a 🔦 documentation change.
Extending the ability of the "multi locale" mode to specify a limited set of locales instead of outputting all locales (i.e. `site.config.available_locales`)

Specify locales in "multi locale" mode

---

.rubocop.yml
bridgetown-core/lib/bridgetown-core/configurations/lit.rb
bridgetown-core/lib/bridgetown-core/configurations/stimulus.rb
bridgetown-core/test/test_apply_command.rb
bridgetown-core/test/test_components.rb
bridgetown-core/test/test_front_matter_defaults.rb
bridgetown-core/test/test_locales.rb
bridgetown-core/test/test_tags.rb
bridgetown-core/test/test_utils.rb

Reviewers - let me know if you want these squashed down to a single commit.

Resolve Rubocop offenses

---

bridgetown-core/lib/bridgetown-core/model/repo_origin.rb

YAMLParser (which is backed by Ruby's YAML parser) appears to have a problem with larger json files.
On one source file, I ran into `Error: YAML Exception reading ../src/_data/posts.json: control characters are not allowed at line 1 column 1`. But when patched to use JSON.parse, it works well.
No tests are needed because it's hit heavily throughout the test suite
A project that I have has a rather large json file as it's data source (2.3M JSON file) and it appears that these larger files have some issues being parsed by the ruby YAML parser (aka. `YAML.load`)  which can also parse json. This data file has been validated with `jq` and `JSON.parse`.

Parse using JSON.parse for more resilient parsing

---

bridgetown-core/lib/bridgetown-core/commands/esbuild/esbuild.defaults.js.erb
bridgetown-core/lib/site_template/package.json.erb
bridgetown-website/config/esbuild.defaults.js
bridgetown-website/esbuild.config.js
bridgetown-website/package.json
bridgetown-website/yarn.lock

This bumps up the esbuild dep version 0.15.x.

Bump up esbuild version in new template and on the BT site

---

CHANGELOG.md
README.md
bridgetown-routes/lib/bridgetown-routes/manifest.rb
bridgetown-routes/lib/bridgetown-routes/manifest_router.rb
bridgetown-routes/test/ssr/config/initializers.rb
bridgetown-routes/test/ssr/src/_routes/localized.erb
bridgetown-routes/test/test_routes.rb

Adds localized routes under the `_routes` folder. This is done by creating all the possible slugs on the fly based on `site.config.available_locales`.
Every route will set `I18n.locale`  and `r.params[:locale]` to the corresponding value extracted from the url slug.
A possible missing piece might be a dedicated config for opting-in/out from the behavior. However, I think that forcing the locale on the file frontmatter could be a good enough alternative and possibly a more granular one.

feat: Localize file-based dynamic routes

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb
bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/lib/bridgetown-core/plugin_manager.rb
bridgetown-core/test/test_plugin_manager.rb

(Note: Rubocop errors prevent the tests to run, I've tested manually for now and wait for #644 to be merged. However, I create the PR now to get your comments on the changes already.)
Bundler added `gems.rb`/`gems.locked` as alternatives to `Gemfile`/`Gemfile.lock` some years ago, mainly to have proper syntax coloring in editors.
Bridgetown has a few places where `Gemfile` is hardcoded, this PR adds support for `gems.rb`. However, in order to assure downwards compatibility, the fallback `Gemfile` is maintained.
Thanks for reviewing and commenting!

Support for gems.rb

---

bridgetown-website/frontend/styles/theme-dark.css

Without this, namespaces end up the same color as the background so they are unreadable. This change makes namespaces the same color as classes and constants.
```ruby
module Foo
class Bar
end
end
```
None.

Fix the readability of namespaces in dark mode

---

bridgetown-core/lib/bridgetown-core/concerns/localizable.rb
bridgetown-core/test/resources/src/_pages/my_directory/third-level-page.en.md
bridgetown-core/test/resources/src/_pages/my_directory/third-level-page.fr.md
bridgetown-core/test/resources/src/_pages/my_other_directory/third-level-page.en.md
bridgetown-core/test/test_locales.rb
bridgetown-website/src/_docs/internationalization.md

This is to avoid an issue where resources with the same slugs under different directories are included in the results.
Closes #660

Filter `Bridgetown::Localizable#all_locales` under the source's parent directory

---

bridgetown-core/lib/bridgetown-core/commands/concerns/actions.rb

Resolves [Performance/RedundantStringChars cop](https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceredundantstringchars)
[Failing build example](https://github.com/bridgetownrb/bridgetown/actions/runs/3785034445/jobs/6434775517)

Autocorrect Rubocop offenses

---

bridgetown-core/lib/bridgetown-core/collection.rb
bridgetown-core/lib/bridgetown-core/resource/base.rb
bridgetown-core/test/test_locales.rb

This should make `resource.data.locale` consistently return symbols.
Resolves #661

Issue 661 mixed locale types

---

bridgetown-website/src/_docs/components/ruby.md

This PR adds documentation around some of the oddities of using View Component.
Closes #665.

Note View Component oddities

---

bridgetown-core/lib/bridgetown-core/configuration.rb

Fixes issue #684
Also removes the missing configuration file warning if an initializers-based config is available

684-restore-localhost-url-with-initializers

---

README.md
bridgetown-website/src/_docs/bundled-configurations.md

- I've adjusted the documentation (if it's a feature or enhancement)
Added details to Shoelace section on the [Bundled Configuration](https://www.bridgetownrb.com/docs/bundled-configurations#shoelace) page for adding additional Shoelace components, like `card`.
Could not get a `card` component working on a new site. Turns out I needed to `import` it via the `./frontend/javascript/index.js` file. So added the details to the website documentation, to help out other noobs like me.
Also added myself to the contributors section of the README file. Congrats to myself for my first open-source contribution. :)

Add details for importing Shoelace

---

bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/lib/bridgetown-core/configuration/configuration_dsl.rb
bridgetown-core/test/ssr/config/initializers.rb
bridgetown-core/test/ssr/config/local_ssr_init.rb

This changes the code which executes Bridgetown's Ruby configuration DSL so initializer files in `config` are loaded via `load` rather than `require`
In testing scenarios (such as plugin gems) when `run_initializers!` may be called many times across a series of tests, the available initializers were blank after the first run. That's because the file to set up those initializers wasn't getting executed by Ruby. We need to `load` rather than `require` those files.
I'm pretty sure this isn't a breaking change, but we'll want to keep an eye on any odd behavior (possibly due to some mistake in attempting to run initializers more than once on the same site config)

fix: load `initializers.rb` instead of require for working tests

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/configuration/configuration_dsl.rb
bridgetown-core/test/test_configuration.rb

While running tests for the `bridgetown-sitemap` plugin, I found that the timezone wasn't being set if it was defined ONLY in the Ruby initializers file. I have no idea why this wasn't a problem yesterday, but it is today.
Upon investigation, I found that the timezone is set as an environment variable but this only happens when the configuration object is instantiated. The initializers run after the object is instantiated. Hence, the timezone value was set in the configuration object, but not in the environment variable meaning it wasn't used in the build.
I've added a `timezone` method to the DSL which sets this value.

Set timezone from initializer Ruby DSL

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/test/helper.rb

This adds a `Bridgetown.reset_configuration!` method which test suites can call before creating new configuration objects prior to site instantiation. This is required so that previously-defined initializers (other than for the site itself i.e. loaded via `config/*`) / source manifests are available once again to a new site config.

Add method to reset config for test suites

---

bridgetown-website/src/_docs/prototype-pages.md

Add warning regarding the placement of `:prototype-term` symbol at the beginning of the title on a prototype page. Quotes are needed to avoid a parsing error.
Added a warning note to prototype-pages.md specifying that quotes must be used around the entire title if the special symbols `:prototype-term` or `:prototype-term-titleize` are to appear first in the title.
Resolves #707

Add warning to prototype-pages.md

---

bridgetown-website/src/_docs/configuration/initializers.md

A very simple typo fix.
But please let me know if I misunderstood the docs and this is not a typo after all.

Fix typo in initializers docs

---

bridgetown-website/src/_docs/plugins.md

Updated a section of the gem based plugin's documentation.
I struggled to get my plugin to work.
It was unclear where I needed to add the plugin's initializer.
I referred to this plugin to figure out where to put the initializer.
https://github.com/ayushn21/bridgetown-sitemap/blob/main/lib/bridgetown-sitemap.rb
I also then saw an error: `undefined method `builder' for main:Object` which I fixed by updating that line to `config.builder`.

Clarify gem based plugin initializer instructions

---

bridgetown-website/src/_docs/plugins.md

This PR adds some context to how we can use keyword arguments to pass values from an end user's initializers.rb file into our plugin's initializer.
Closes: https://github.com/bridgetownrb/bridgetown/issues/716

Clarify adding keyword args to plugin initializers

---

bridgetown-website/src/_docs/philosophy.md

Last sentence of first paragraph on this page:
https://www.bridgetownrb.com/docs/philosophy
Before:
...it’s important to lead with a set of basic principles **what** will help guide...
After:
...it's important to lead with a set of basic principles **that** will help guide...

Refactor wording in philosophy.md

---

bridgetown-website/frontend/styles/global.css
bridgetown-website/src/_layouts/default.serb

Adds a skip link which is visually hidden unless it receives focus.
Helps with resolving #724.

Add main content skip link to website

---

bridgetown-website/frontend/styles/global.css
bridgetown-website/frontend/styles/theme-dark.css

Avoids invisible bold text in dark mode.
Example docs page showing the issue (when in dark mode): https://www.bridgetownrb.com/docs/front-matter#the-power-of-ruby-in-front-matter
New styling example below:

Avoid invisible code highlight for bold text in dark mode

---

bridgetown-builder/lib/bridgetown-builder/dsl/http.rb
bridgetown-builder/test/test_http_dsl.rb
bridgetown-website/src/_docs/plugins/external-apis.md

This change includes two related items:
1. Fixes the handling of headers for HTTP DSL requests. They were improperly being sent as a `headers` parameter and now will be sent as actual headers.
2. Adds sending parameters to the URL via keyword arguments. This is valuable because constructing the query string parameters directly is tedious and prone to typos.
Closes #630

Fix passing headers and add passing parameters to HTTP DSL

---

bridgetown-core/lib/bridgetown-core/collection.rb

For context:
> sandstrom Yeah, seems like a mistake. We could just switch from model.locales to model.attributes[:locales] which wouldn't trigger a warning. The warning is for the benefit of users, not for our internal purposes. -- jaredcwhite
More details in the issue below.
Fixes #744

Fix locales warning bug

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/errors.rb
bridgetown-core/lib/bridgetown-core/rack/routes.rb
bridgetown-core/lib/bridgetown-core/utils.rb
bridgetown-core/lib/bridgetown-core/utils/loaders_manager.rb
bridgetown-core/lib/roda/plugins/bridgetown_server.rb

When there's an exception which would normally get logged to the terminal, now that error is also surfaced on the website itself through the dev reload process. By seeing the error show in a dialog on the page, you're altered to check your logs which is much nicer than just having to "guess" there's a problem if the logs aren't immediately visible on your desktop.
Resolves #718

Display build error on the page in a dialog in dev

---

bridgetown-website/src/_pages/plugins.serb

And it could also be considered a 🐛 fix.
By default the github api returns [30 results per page](https://docs.github.com/en/rest/search?apiVersion=2022-11-28#search-repositories) on a repository search. At this time there are 36 repositories in github with the [`bridgetown-plugin`](https://github.com/topics/bridgetown-plugin) topic.
This temporarily fixes the issue by setting a `per_page=100` parameter on the api call. Once there are more than 100 plugins, the code will need to make multiple calls to get all the plugins. That will be a good problem to have 😺

Fix 30 repo limit on bridgetown-plugin github topic search

---

bridgetown-core/lib/bridgetown-core/commands/esbuild/esbuild.defaults.js.erb
bridgetown-core/lib/bridgetown-core/commands/esbuild/jsconfig.json
bridgetown-core/lib/bridgetown-core/commands/esbuild/setup.rb
bridgetown-core/lib/bridgetown-core/commands/esbuild/update.rb
bridgetown-core/lib/bridgetown-core/utils/aux.rb
bridgetown-core/lib/site_template/frontend/javascript/index.js.erb
bridgetown-core/lib/site_template/package.json.erb
bridgetown-core/test/test_new_command.rb
bridgetown-website/src/_docs/frontend-assets.md

In the process of upgrading esbuild to the latest version (along with PostCSS and other dependencies), I encountered some super weird issues with the watch process and CSS imports (aka index.css). Sometimes the files wouldn't rebuild at all when edited. Other times it would happen repeatedly.
I eventually tracked it down to some change back in 0.16.8+ around dependency resolution. There was a later change involving the `nodePaths` option, which seems not to have fully fixed this issue I saw.
I ended up going down a very different path. Rather than try to use esbuild's `nodePaths` config option in order to get nice imports like `import "index.css"` in `index.js`, I went with a more "standard" sort of path alias setup. esbuild can read in `jsconfig.json` and evaluate path aliases, which …

Update to esbuild 0.17

---

bridgetown-core/lib/bridgetown-core/filters/localization_filters.rb
bridgetown-core/lib/bridgetown-core/helpers.rb
bridgetown-core/lib/bridgetown-core/tags/l.rb
bridgetown-website/src/_docs/internationalization.md

Notes:
- I haven't found tests for `I18n.t` that I could duplicate, but maybe I haven't looked in the right places. I'm not familiar with minitest.
- I've adjusted the documentation.
- The ci/build script cannot run on my machine, rbenv refuses to compile ruby 2.7.2. 
- While browsing the code, I sumbled upon `date_to_string` and `date_to_long_string`, which could be rewritten using `I18n`. 
Add `l` filter/tag/shortcut to `I18n.l`.
Closes #753

Add I18n localization shortcut "l" alongside "t"

---

bridgetown-website/src/_docs/configuration/options.md

This PR removes a trailing comma in YAML configuration options documentation
When copied and pasted, the resulting YAML content is now valid.

doc: remove trailing comma in configuration options

---

bridgetown-website/src/_docs/deployment.md

Add documentation about serving compressed assets for GitLab Pages.
GitLab pages can serve compressed files if they are present and if the browser supports receiving compressed files. Both [GZip] & [Brotli] are exposed here. Brotli has a better compression ratio. GZip is more widely supported.
[GZip]: https://fr.wikipedia.org/wiki/Gzip
[Brotli]: https://fr.wikipedia.org/wiki/Brotli
You can see an up & running example on my personal blog repository:  
https://gitlab.com/strigocc/code/-/blob/main/.gitlab-ci.yml

doc: GitLab Pages serving compressed assets

---

.gitignore
Gemfile.lock
bridgetown-core/lib/bridgetown-core/filters.rb

This is a 🔧 tooling change.
This change stops ignoring the `Gemfile.lock` and checks it into the repository. This is a best practice to make contributing easier for new (and current) contributors.
One large paper cut is to get all of your changes to pass locally then have CI fail because of updates in the linting pipeline that aren't compatible with — in particular — code that you did not touch.
By checking `Gemfile.lock` in, it ensures that all contributors are working from the same versions of dependencies that the CI server is running.
In addition, this change also locks Rubocop to the newest version that relies on `rubocop-ast` <= 1.28.0. That version and 1.29.0 have a parsing bug in them that won't parse one of the files in Bridgetown's source code and error out. Also, newer versions …

Lock Rubocop to latest version that passes

---

bridgetown-core/lib/bridgetown-core.rb

`Configuration::DEFAULTS` uses `Dir.pwd` to determine the root directory for the configuration. This means that lazy loading the file using `autoload` makes the root path for configuration non-deterministic depending on the directory location the first time you try to use `Bridgetown::Configuration`.
This has a knock-on effect of making tests fail nondeterministically.
By eager loading the configuration file, we can reduce this nondeterminism by ensuring the value is set the same way every time.
This can be reproduced with the following on 7ecd7f6ab8943fc0cb4562ed25d4ddfdb9442f21.
<details>
<summary>Reproduction</summary>
```bash
BYPASS_RESOURCE_TEST=true bundle exec ruby -Itest:lib -e 'require "./test/fixtures/test_automation.rb" ; require "./test/test_ansi.rb" ; …
```

Eager load to make DEFAULTS deterministic

---

bridgetown-website/src/_docs/frontend-assets.md

Provide examples for referencing static files with Esbuild and Webpack.
Esbuild and Webpack have a slightly different strategy for referencing static files that are processed by
them. Provide examples to ease use.
Alternatively, we can include those examples directly in the templates, optionally in a commented-out state.
Feel free to close PR if obvious or incorrect.
Thank you!

Clarify how to reference static files on the frontend from Webpack/Esbuild

---

bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/lib/bridgetown-core/utils/loaders_manager.rb
bridgetown-core/lib/site_template/config/initializers.rb
bridgetown-website/src/_docs/configuration/initializers.md
bridgetown-website/src/_docs/resources.md

Summary
Since #793 is a breaking change I've introduced this PR that allows you to configure an inflector. The documentation is updated to show you how to configure ActiveSupport::Inflector and notes that it will become the default in v2.0.

Add Configurable Inflector for Zeitwerk

---

bridgetown-core/lib/bridgetown-core/helpers.rb
bridgetown-core/test/test_ruby_helpers.rb

- When passing a block to `link_to` the additional options were being dropped. 
- When passing a block to `link_to` in ERB, the block needs to be captured or the block is not inside the link element.

Fix `link_to` when passed block

---

bridgetown-core/lib/bridgetown-core/commands/esbuild/esbuild.defaults.js.erb

There's been an ongoing effort to ensure very few code changes to your project result in a crash when the dev server is running. We've made great strides, but certain PostCSS build errors were still resulting in an esbuild crash—and furthermore, it was hard even to tell why.
With this PR, esbuild won't crash, your site's stylesheet will temporarily go wonky (alerting you that something's off), and the exact nature of the error plus file path, line, and column numbers will explain where you should look to resolve the issue.

Catch error and log when PostCSS conversion fails

---

bridgetown-core/lib/bridgetown-core/concerns/localizable.rb

This is a 🐛 bug fix. 
I'm not sure if this is the right way to go about this. Additionally, there are no tests because I couldn't find any examples of testing paginate at all.
Fixes #789

Fixed localization of paginated resources error

---

bridgetown-core/lib/bridgetown-core/rack/boot.rb

I recently got confused working on a project because I was dealing with a syntax error on a Roda routes file in the `server/routes` folder, and upon fixing it I didn't see any log that the file had gotten reloaded. Turns out, we don't actually print a log message on server route reloads! This PR resolves that issue.

Show a reloading log for Roda routes in the server folder

---

bridgetown-core/lib/bridgetown-core/yaml_parser.rb
bridgetown-core/test/fixtures/extra_yaml.yml
bridgetown-core/test/test_yaml_parser.rb

By default, Bridgetown expects to be able to load its special Rb class for YAML front matter. The original implementation made it hard to have extra permitted classes in front matter while retaining that expectation.
This change makes it so the default permitted classes are merged into any passed permitted classes across both string and file loading.
While digging into ways that we could have a consistent YAML store for #777, I discovered this papercut.

Allow consistent permitting classes

---

bridgetown-core/lib/bridgetown-core/plugin_manager.rb

Auto-detect how to install dependencies of plugins to improve the story of using any package manager
Related to #609 
This doesn't fix it. But this allows you to opt-out of yarn and use whatever package manager you want. We could also just bail if we can't find a `yarn.lock` or maybe check an ENV var like `NO_YARN_INSTALL` or something?

auto-detect package manager in the plugin manager

---

bridgetown-website/src/_docs/components/liquid.md

I think this is a typo in /docs/components/liquid#rendering-liquid-components-from-ruby-based-templates

Fix typo in liquid.md

---

bridgetown-website/src/_docs/deployment.md

This updates the GitLab Pages section of the deploy documentation to use [`!reference` tags][1] to reuse the shared config between the `pages` and `test` jobs.
I'm working on getting a bridgetown project setup to deploy on GitLab Pages and I copied the provided example to get started with. It did work, but I noticed that there was a lot of duplicate "setup" code and wanted to combine that so that for example, if I want to update the node version I only have to do that in one place instead of two.
It's worth noting that the linked GitLab docs say to use the special `extends` keyword over built-in yaml features. The reason I'm using `!reference` instead is because:
> You can use `extends` to merge hashes **but not arrays**
[1]: …

Update GitLab Pages deploy example to use !reference tag

---

bridgetown-core/lib/bridgetown-core/configurations/netlify/netlify.sh
bridgetown-core/lib/bridgetown-core/configurations/netlify/netlify.toml

- CSS and JS path are incorrect
- `NETLIFY_IMAGES_CDN_DOMAIN` doesn't appear to exist anymore and isn't documented (https://docs.netlify.com/configure-builds/environment-variables/#read-only-variables)
- Netlify removed all post processing besides `pretty_urls`
Fixes #823

Update Netlify configuration

---

bridgetown-core/lib/bridgetown-core/helpers.rb
bridgetown-core/test/source/src/_locales/en.yml
bridgetown-core/test/test_ruby_helpers.rb
bridgetown-website/src/_docs/internationalization.md

- Added support for relative translation keys (ex: `t('.foo')`).
- Added support for automatically marking translation keys ending with `_html` as `html_safe`.
- Renamed methods to `translate` and `localize` with aliases of `t` and `l`.
- Added tests.
Closes #837

Improve localization helpers

---

bridgetown-website/config/esbuild.defaults.js

This PR adds a few file extensions as a file type to the list in `esbuild.defaults.js`:
* `.jpeg`
* `.avif`
* `.jxl`
* `.webp`
With this change, [WebP](https://en.wikipedia.org/wiki/WebP), [AVIF](https://en.wikipedia.org/wiki/AVIF) and [JPEG-XL](https://en.wikipedia.org/wiki/JPEG_XL) images are supported in the same way that PNG and JPEG are supported. It also adds `.jpeg` as the alternative file extension for JPEG files.
[This is from a discussion about me failing to fingerprint images](https://github.com/bridgetownrb/bridgetown/discussions/835)

esbuild: Add webp to the file endings loaded as files

---

bridgetown-core/lib/bridgetown-core/commands/console.rb

Move the `site` and `collections` console commands to be local variables in the IRB shell.
Console methods have precedence over Ruby methods with the same name. This means that any method name or local variable will be clobbered by the IRB commands `site` and `collections`. This presents an issue when using the IRB or Pry object navigation features, e.g.
```
3.0.6 :001 > cws site
irb: warn: can't alias source from irb_source.
#<Bridgetown::Site >
3.0.6 :002 > render
/Users/mattpace/.rvm/gems/ruby-3.0.6/gems/activesupport-7.1.2/lib/active_support/isolated_execution_state.rb:70:in `state': stack level too deep (SystemStackError)
from /Users/mattpace/.rvm/gems/ruby-3.0.6/gems/activesupport-7.1.2/lib/active_support/isolated_execution_state.rb:38:in `[]'
from …
```

Move site and collections console commands to locals

---

CHANGELOG.md
README.md
bridgetown-core/lib/bridgetown-core/configurations/stimulus.rb

When using the Stimulus Configuration, the generated code for loading Stimulus controllers makes a couple `replace` calls to translate a path to a Stimulus identifier. 
This means that if you have a controller whose filename is `do_a_thing_controller.js`, this gets translated into the Stimulus identifier `do-a_thing`, when one would expect it to have been `do-a-thing`. There case for controllers nested in directories is similar.
With the way Stimulus currently works, it's incredibly annoying to debug this, because there are no warnings. Your controller just seemingly _doesn't work_.
When building my personal site with Bridgetown and Hotwire, I added a controller that used multiple underscores, and then spent an embarrassing amount of time trying to figure out what I …

Use Global Regex for Stimulus Configuration

---

bridgetown-core/lib/bridgetown-core/commands/esbuild/esbuild.defaults.js.erb

Follow up to https://github.com/bridgetownrb/bridgetown/pull/863#issuecomment-2003220088
This adds support for additional image file extensions to the bridgetown esbuild configuration.
@matiaskorhonen pointed out that the previous change missed the change to the `esbuild.defaults.js.erb` file.

Add image formats to esbuild.defaults.js.erb

---

Gemfile.lock
bridgetown-core/bridgetown-core.gemspec
bridgetown-core/lib/bridgetown-core/rack/routes.rb
bridgetown-core/lib/bridgetown-core/utils.rb
bridgetown-core/lib/roda/plugins/bridgetown_server.rb

Rack 3 formalised bi-directional connections into the spec and implementations. This allows us to pass a proc instead of an array of strings in the Rack response.
Using this method, we can significantly simplify the code for live reloads. 
This was a result of my spontaneous deep dive into Ruby fibers, the Async gem, and by extension, Rack 3 and Falcon.
Background info:
https://youtu.be/yXyj9wlkJKM?si=prkP1nNCfA8WNBSU&t=1396
This will only work in Rack 3. I think we should set that as a minimum requirement for BT2.0 unless there's a good reason not to?
Fixes https://github.com/bridgetownrb/bridgetown/issues/861

Use rack 3 proc responses for SSE live reload

---

bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/lib/bridgetown-core/front_matter/loaders/ruby.rb
bridgetown-core/lib/bridgetown-core/front_matter/loaders/yaml.rb
bridgetown-core/lib/bridgetown-core/model/builder_origin.rb
bridgetown-core/lib/bridgetown-core/ruby_template_view.rb
bridgetown-core/test/resources/src/_layouts/default.erb
bridgetown-core/test/resources/src/_pages/second-level-page.en.md
bridgetown-core/test/resources/src/_pages/second-level-page.fr.md
bridgetown-core/test/test_locales.rb
bridgetown-routes/.rubocop.yml
bridgetown-routes/lib/bridgetown-routes/code_blocks.rb
bridgetown-routes/lib/roda/plugins/bridgetown_routes.rb
bridgetown-routes/test/ssr/src/_routes/bare_route.rb
bridgetown-routes/test/ssr/src/_routes/howdy.erb
bridgetown-routes/test/ssr/src/_routes/localized.erb
bridgetown-routes/test/ssr/src/_routes/nested/[slug].erb
bridgetown-routes/test/test_routes.rb

After writing `data.xyz` a zillion times, you start to wonder if you can just write `xyz`. 😂
And in the continuing saga of questioning boilerplate, I wondered if I could get rid of `render_with {}` (which works due to copying local block variables down to the template) while at it.
So this is now possible in a dynamic Roda route:
```erb
---<%
name = "World"
%>---
Hello <%= name %>
```
Nice! 😌
Of course this will still work equally well:
```erb
---<%
render_with do
name "World"
end
%>---
Hello <%= name %>
```
And regular front matter in static resources:
```md
---
title: My Page
---
```
For folks who for whatever reason don't like this simplified syntax, the `support_data_as_view_methods` option can be set to `false` in the Bridgetown config, and then `data.foo` syntax is still mandatory. …

Simplify access to data syntax and Roda rendering

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/component.rb
bridgetown-core/lib/bridgetown-core/model/base.rb
bridgetown-core/lib/bridgetown-core/resource/base.rb
bridgetown-core/lib/roda/plugins/bridgetown_server.rb
bridgetown-core/lib/roda/plugins/bridgetown_ssr.rb
bridgetown-core/test/ssr/config.ru
bridgetown-core/test/ssr/server/routes/hello.rb
bridgetown-core/test/ssr/server/routes/render_resource.rb
bridgetown-core/test/ssr/src/_components/UseRoda.rb
bridgetown-core/test/test_ssr.rb

Some cleanup and enhancements made possible by utilizing Roda's custom_block_results plugin more effectively…including even letting you return components as route results. There's some more cleanup I want to do that will enable #561 as well. This is also the start of a new evaluation of places in the framework where we can leverage the "callable" object pattern.
Oh yeah, also added in a `site` alias so no more having to remember `bridgetown_site` in Roda routes. Hurray!

Make it easy for Roda routes to render "callable" objects

---

bridgetown-website/src/_docs/installation/upgrade.md

I had an error that didn't quite match the upgrade guide and didn't quite give enough info what was happening.
Full error (for anyone searching)
```
➜  docs git:(konnorrogers/major-overhaul) ✗ bin/bridgetown start
[Bridgetown]           Starting: Bridgetown v2.0.0.beta2 (codename "(TBD!)")
[Bridgetown]
[Bridgetown]    Booting Puma at: http://0.0.0.0:4000
[Bridgetown]
Progress: resolved 1, reused 0, downloaded 0, added 0
 WARN  deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
 WARN  deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
 WARN  2 deprecated subdependencies found: @material/mwc-icon@0.25.3, inflight@1.0.6
Packages: +1 -3
+---
 WARN  2 deprecated subdependencies found: @material/mwc-icon@0.25.3, …
```

Add additional possible error for roda server

---

bridgetown-core/lib/bridgetown-core/concerns/site/fast_refreshable.rb
bridgetown-core/lib/bridgetown-core/resource/base.rb

As it says on the tin. Individual resources with locales set as well as multi resources are now supported.
**Note:** there _may_ be remaining edge cases where generated pages are concerned, but if so I would consider those in the realm of a 2.x patch and not to hold up the initial 2.0 release.

Support i18n with fast refresh (rerender multiple locales)

---

bridgetown-core/lib/roda/plugins/bridgetown_server.rb

I apologize that I have not read the project goals, future roadmap, or code of conduct.  If for any reason I'm violating something, please feel free to close.
This is a 🙋 feature or enhancement. It's actually a refactoring, but I think of removing duplication as an enhancement.
- I've **not** added tests (if it's a bug, feature or enhancement).  This is a refactoring and should not affect behavior.
- I've **not** adjusted the documentation (if it's a feature or enhancement). This is a refactoring and should not affect behavior.
- I've **not** run the test suite locally (I've forked the repo, but not even cloned it locally). However, I enabled GitHub Actions in my fork, and CI passed on my fork.
By choosing an appropriate argument to `on`, based on the base path, we don't need a separate …

Avoid duplication in r.bridgetown implementation

---

bridgetown-core/lib/bridgetown-core/front_matter/defaults.rb
bridgetown-core/test/test_front_matter_defaults.rb

Ensure front matter defaults are dot access hashes

---

bridgetown-core/lib/bridgetown-core/configuration.rb
bridgetown-core/test/test_site.rb

Fixes #624 
Also ensures when setting `exclude` via initializer config, we'll preserve our default excludes as well.

Preserve the `_bridgetown` default value in `keep_files` config

---

bridgetown-core/lib/bridgetown-core/converters/erb_templates.rb
bridgetown-core/lib/bridgetown-core/converters/serbea_templates.rb

Resolves #957 
I'm not honestly sure this is a huge win for SSG, but it's something. Maybe 5% or so boost across hundreds of pages which use the same layout. It'll be more important for SSR performance though (I think).

Cache instantiated template objects for ERB and Serbea

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/concerns/site/fast_refreshable.rb
bridgetown-core/lib/bridgetown-core/concerns/site/writable.rb
bridgetown-core/lib/bridgetown-core/rack/boot.rb
bridgetown-core/lib/bridgetown-core/rack/routes.rb
bridgetown-routes/lib/roda/plugins/bridgetown_routes.rb

This uses a special hidden file for watching for live reload.
Also includes some Routes plugin-related fixes as well as making those go on the Fast Refresh track
Fixes #940

Switch to `.bridgetown-cache/live_reload.txt` for live reload

---

bridgetown-core/lib/bridgetown-core/collection.rb
bridgetown-core/test/features/test_pagination.rb
bridgetown-paginate/lib/bridgetown-paginate/paginator.rb
bridgetown-website/src/_docs/resources.md

Resolves #913 
You can now write:
```ruby
paginator.each { it } # loop through resources
```

Add Enumerable to Paginator

---

bridgetown-core/lib/bridgetown-core.rb
bridgetown-core/lib/bridgetown-core/rack/boot.rb

In order to start Bridgetown by running the web server directly (`bundle exec puma`), we need to `require "bridgetown"` in the boot file.
Without it, we get all sorts of uninitialized constant errors.  
This is one of those fixes where I'm not sure what I'm doing, and whether it'll have any bad consequences. I just hammered it until it worked and seems to be working fine in my tests. 
@jaredcwhite is this a valid fix? Please don't merge it until we know for sure it's not gonna make things catch fire haha.
Part of https://github.com/bridgetownrb/bridgetown/issues/946

Require bridgetown when booting from Rack

---

bridgetown-core/lib/bridgetown-core/commands/plugins.rb
bridgetown-core/test/test_plugins_command.rb

This PR excludes `init (Initializer)` from the count of registered plugins when the `bin/bridgetown plugins list` command is run. See #770 for details.
Fixes #770

WIP: Exclude init initializer from plugins list command count

---

bridgetown-website/src/_docs/frontend-assets.md

sass deprecated the @import function. the @use function should work in its place.  [@import in sass docs](https://sass-lang.com/documentation/at-rules/import/), [sass deprecation blog entry](https://sass-lang.com/blog/import-is-deprecated/)
No github issues, just deprecation warning to avoid.

doc update. sass deprecated @import, @use should work in place.

---

bridgetown-foundation/lib/bridgetown/foundation/questionable_string.rb

This is a bug fix.
When using rake with Ruby 3.4 I get a warning:
> ~/.gems/gems/bridgetown-foundation-2.0.0.beta4/lib/bridgetown/foundation/questionable_string.rb:8: warning: string returned by :production?.to_s will be frozen in the future
**To reproduce**
```bash
bridgetown plugins new XYZ
cd XYZ
rake
```

fixed frozen string warning for ruby 3.4

---

bridgetown-website/src/_data/bridgetown_variables/global.yml
bridgetown-website/src/_data/bridgetown_variables/site.yml
bridgetown-website/src/_docs/variables.md

noted differences I'm aware of between liquid and ruby templating
For ##992

doc/variables differences for config and env between liquid and ruby.

---

bridgetown-website/src/_docs/deployment.md

Add a third-party to the deployment guides.
Hi! Supranode founder here. I would like to include Supranode as one of the available third-party providers for Bridgetown deployments.

Add Supranode to deployment docs

---

bridgetown-website/src/_docs/cookbook.md
bridgetown-website/src/_docs/cookbook/collection_by_years.md
bridgetown-website/src/_docs/cookbook/helpers_date.md
bridgetown-website/src/_docs/cookbook/helpers_example.md
bridgetown-website/src/_docs/cookbook/monthly_archives.md

This is a 🔦 documentation enhancement. 
This provides an example of an alternative approach to pagination. 
It proposes a new documentation section: cookbook for code examples.
The technique could be considered a workaround for #807.

propose cookbook with pagination alternative example

---

bridgetown-core/lib/bridgetown-core/resource/base.rb

Resolves #977 
The problem is the data originally read into each locale's resources was getting overridden by newly-loaded front matter from the origin model. This now ensures if the model's locale is `multi` we preserve the actual locale of the derived resource.

fix: multi-locale in front matter works with Fast Refresh

---

bridgetown-core/lib/bridgetown-core/component.rb
bridgetown-foundation/lib/bridgetown/foundation/questionable_string.rb

Pass options hash as keyword arguments to the `partial` method

---

bridgetown-website/src/_docs/configuration.md
bridgetown-website/src/_docs/configuration/environments.md
bridgetown-website/src/_docs/content/pagination.md
bridgetown-website/src/_docs/internationalization.md
bridgetown-website/src/_docs/plugins/external-apis.md
bridgetown-website/src/_docs/prototype-pages.md
bridgetown-website/src/_docs/template-engines.md

I've gone through the doc looking for examples in legacy yaml and added equivalent initializers code with multilang. configuration.md had both examples, but they were not equivalent, I updated the ruby example to include all options in the yaml example. 
I also added a note on configuration processing order.

add initializers.rb examples to match legacy yaml examples

---

bridgetown-website/src/_docs/content/pagination.md

After helping someone on discord who was having trouble with pagination, I found two spots that needed update.

add 2 ruby/erb examples to pagination.

---

bridgetown-core/lib/bridgetown-core/collection.rb
bridgetown-core/test/test_collections.rb

Before the fix, this would not work:
```ruby
Bridgetown.configure do |config|
config.collections = {
"docs" => {
"output" => true,
"sort_by" => :order,          # ❌ This would fail
"sort_direction" => :descending # ❌ This would fail
}
}
end
```
After the fix, both strings and symbols work:
```ruby
Bridgetown.configure do |config|
config.collections = {
"docs" => {
"output" => true,
"sort_by" => :order,          # ✅ Now works
"sort_direction" => :descending # ✅ Now works
}
}
end
```
Or using strings (this always worked)
Fixes #975

Allow `sort_by` and `sort_direction` to accept symbols in collection metadata

---

bridgetown-core/lib/bridgetown-core/model/base.rb
bridgetown-core/lib/bridgetown-core/signals.rb

In [a change to Ruby 3.4][1], the core team made it so `Symbol#to_s` returns a "chilled" string, which is a String that will be frozen in future releases of Ruby.
This change makes two cases that were raising warnings for me on Ruby 3.4.5 use a dup-and-modify approach for handling assignment calls within `method_missing` implementations.
[1]: https://bugs.ruby-lang.org/issues/20350
See ruby/ruby#12065

Handle Symbol#to_s returning chilled strings

---

bridgetown-core/lib/bridgetown-core/commands/build.rb
bridgetown-core/lib/bridgetown-core/commands/start.rb
bridgetown-core/lib/site_template/config/puma.rb

Fixes #996 (sort of)
I simply couldn't come up with a clean way to honor the port number that's directly in `config/puma.rb`, so I updated our template file for that to indicate that's not the place to be changing the number.
Beyond that, I'm doing the funky-but-it-works method of checking if the initializers config _will_ init `dotenv` via. regex — if so, it will preemptively load dotenv before determining the port value. In addition, I've clarifed the load order of the port config value so it works like so:
1. CLI
2. BRIDGETOWN_PORT env var
3. YAML config (if present)
4. 4000
Alas, we also have the issue where we can't get the port number from the initializers config as that config is loaded _after_ Puma boots because the server and the static build process are two separate init …

Load dotenv before booting Puma if it will be initialized

---

CHANGELOG.md
bridgetown-core/lib/bridgetown-core/commands/new.rb
bridgetown-core/test/test_new_command.rb

This is a 🐛 bug fix. 
This fixes #1006 - invoking `new` command with additional parameters won't use them to create a folder. Additionally this makes `new` command more consistent with regular shell usage, where parameters containing spaces should be wrapped with double quotes.
Fixes #1006

Fix: Don't take all arguments to create a new site (#1006)
